goadesign/goa

design/validation.go

Protect against invalid definition where a media type has no view.

Fix potential crash in link validation

---

design/dsl/runner.go

So that validation errors don't hide them.

Report syntax errors before validation errors

---

design/definitions.go
design/dsl/attribute.go
design/dsl/runner.go
goagen/codegen/types.go

When validating attributes with primitive type.
Make validation failure error messages clearer.

Fix validation code bug

---

goagen/codegen/types.go

when validating required string attributes

Fixed missing }

---

goagen/gen_app/writers.go

Always generate the payload type

---

goagen/gen_app/writers.go

Fix newline breaks after param validation

---

goagen/gen_main/generator.go
middleware.go

respond 500 on recover instead of falling through to "unhandled request"
change generated middleware to log response after recover

respond_500_to_panic

---

application.go
glide.yaml

@raphael added built-in support for graceful shutdown to app.Run()
added app.RunInBackground() and app.Shutdown() for cases of apps that do more than run a web service

graceful_shutdown

---

goagen/gen_main/generator.go

So that it mounts the swagger controller but not the schema controller.

Fix main generator

---

goagen/codegen/types.go
goagen/codegen/types_test.go

* `dictionary` instead of `map[string]interface{}`
* `array` instead of `[]interface{}`
References #50

Update error message generated to be generic, #50

---

.gitignore
client.go
examples/cellar/client/cellar-cli/main.go
goagen/gen_client/generator.go

Client generation fixes and improvements.
* Properly close response body io reader (thanks @on99).
* Properly handle `--help` flag.
* Prevent double dumping of response body with `--dump`.

Client gen

---

design/definitions.go
design/dsl/metadata.go

Added Metadata to many of the base DSL types to allow for key/value pairs to be attached to most of the nodes on the DSL tree.
UseCase: In custom generators I need the ability to annotate things that aren't strictly DSL related.

Add Metadata

---

design/dsl/media_type.go
design/types.go
examples/cellar/app/contexts.go
examples/cellar/app/media_types.go
examples/cellar/app/user_types.go
examples/cellar/design/media_types.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/codegen/validation.go
goagen/gen_app/writers.go

Fixes #97. This PR makes if possible for type definitions to refer to each other.
It also fixes a few issues with code generation around user types.
Finally it gets away with a few unnecessary use of temporary variables.
The basic idea for handling cyclic definitions is to introduce intermediary methods
that handle the type marshaling and unmarshaling and to call these methods instead
of generating the code statically (in which case the code generation would loop
indefinitely).

Handle recursive definitions

---

design/dsl/api.go

This is to reflect the removal of limit on the number of parameters that a ResponseTemplate definition may use.
Fix #91.

Adjust ResponseTemplate comment 

---

design/dsl/api_test.go
design/dsl/resource_test.go
design/validation.go

The implementation would fail if the base path defined only one parameter.

Fix bug with resource BaseParams DSL.

---

Makefile

So that tests that depend on it use the latest.

Build goagen before running tests

---

design/dsl/action.go
service.go
service_test.go

BREAKING CHANGE: to open the door for supporting multiple Content-Type in
incoming requests, we now only decode the req.Body as JSON when the client
specifies "application/json" in the "Content-Type" header, or when that
header is empty.
Eventually, we will implement other decoders to build up the payload.
This change allows someone to receive an incoming "application/octet-stream"
by simply reading the "ctx.Request().Body" .. or handle other types
in the controller.
[Also includes a minor doc addition.]

BREAKING: decode request.Body only with the right Content-Type header

---

design/dsl/media_type.go
design/dsl/type.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/gen_app/generator.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go

Properly handle the case where a versioned type uses
an unversioned type in marshaling and unmarshaling code.

Fix issues introduced by versioning support.

---

graceful.go

Graceful application currently cancels existing requests by canceling
the context. If this context is used in http requests, the requests get
canceled and thus the graceful application is not very graceful. This
change makes the cancelation configurable.

Make cancelation configurable for Graceful application

---

design/definitions.go
design/dsl/api.go
design/dsl/runner.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go

This PR fixes #127. Before this PR the following DSL:
```go
var MyType = Type("my_type", func() {
Attribute("foo", Integer)
})
```
would generate the following data structure:
```go
type MyType struct {
Foo int
}
```
The changes in this PR produce the following:
```go
type MyType struct {
Foo *int
}
```
Required attributes still generate non-pointer fields:
```go
var MyType = Type("my_type", func() {
Attribute("foo", Integer)
Required("foo")
})
```
generates:
```go
type MyType struct {
Foo int
}
```
The changes also remove the `HasXXX` fields that were generated in the contexts. The client code should now check whether the pointer is nil instead.

Make basic type optional data structure fields pointers

---

context.go
context_test.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
middleware.go
middleware_test.go
service.go
service_test.go

Rename the JSON method of Context to Respond to reflect the
fact that multiple encodings are now supported. Rename the
previous Respond into RespondBytes.

Use service encoders to marshal response.

---

design/dsl/action.go
design/dsl/api.go
design/dsl/attribute.go
design/dsl/media_type.go
design/dsl/resource.go
design/dsl/response.go
design/dsl/type.go

Action, Attribute, Type, etc have whitespace issues.  Once I got started, I
couldn't stop.  Fixes patterned after encoding/gob.  Use tabs in all of the
preformatted text blocks, even preceeding trailing line comments.  Tab width is
8.

Fix whitespace in dsl godoc comments

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

If a payload has no required fields or other validation triggers a Validate() function is not generated.  The controllers don't  have this check.  This fix generates a Validate() function even if there are no validations, and simply returns a nil error.
{EDIT} Instead this change doesn't test Validate() if it shouldn't.

Don't call Validate() if there is no Validate() function on a payload

---

Makefile
goagen/gen_main/generator.go
service_test.go

Middleware is now `github.com/goadesign/middleware` instead of `github.com/goadesign/middleware/middleware`.

Update to match middleware move

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

Add nil check before recursing into child object.

Properly handle object attributes in generated validation code.

---

.gitignore
_integration_tests/integration_test.go
_integration_tests/readme/design/design.go

These tests would be aimed at finding generating code or with generated code.
e.g: right now the example in README generates invalid code:
```
--- FAIL: TestBootstrapReadme (4.59s)
integration_test.go:16: exit status 2
./main.go:20: cannot use service (type "github.com/goadesign/goa".Service) as type "github.com/raphael/goa".Service in argument to NewOperandsController:
"github.com/goadesign/goa".Service does not implement "github.com/raphael/goa".Service (wrong type for ErrorHandler method)
have ErrorHandler() "github.com/goadesign/goa".ErrorHandler
want ErrorHandler() "github.com/raphael/goa".ErrorHandler
./operands.go:15: cannot use OperandsController literal (type *OperandsController) as type app.OperandsController in return argument:
*OperandsController does not implement …
```

Add integration tests to generate and build code

---

goagen/codegen/types.go
goagen/codegen/types_test.go

the function generated had no return statement.

add missing return at the end of the function

---

.travis.yml

- Use the latest releases of go 1.4 and 1.5.
- Enable OSX builds.
- Allow go tip builds to fail.

Add more Travis CI options

---

design/api.go
design/apidsl/attribute.go
design/apidsl/media_type_test.go
design/definitions.go
design/example.go
design/random.go
design/types.go
goagen/gen_js/generator.go
goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger.go

Add Example DSL to allow users define their custom example, so goa can generate swagger specs with examples. If not given, goa will automatically generate a random value for the users.

Add Example DSL

---

goagen/codegen/types.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
mux.go

Also use APIVersion as context field to store version to
avoid clash with Version.

Use :api_version as default version param

---

service.go

… this was due to an unescaped `err` being added to the msg string making the JSON invalid.
E.g. here's what it was returning:
```json
"{\"kind\":\"invalid request\",\"msg\":\"invalid encoding: [{\"id\":8,\"title\":\"value does not match validation pattern\",\"msg\":\"raw.principal.href must match the regexp \\\"^/grs/(users|groups)/(\\\\\\\\d+)$\\\" but got value \\\"/grs/users/1a\\\"\"}]\"}"
```
Now it will return as a JSON object, and probably will work for XML as well:
```json
{
"kind": "invalid request",
"msg": "invalid encoding: [{\"id\":8,\"title\":\"value does not match validation pattern\",\"msg\":\"raw.principal.href must match the regexp \\\"^/grs/(users|groups)/(\\\\\\\\d+)$\\\" but got value \\\"/grs/users/1a\\\"\"}]"
}
```
TODO: it would be extra nice if the error details …

ACL-214 400 errors were returned as a string containing a malformed JSON object

---

goagen/codegen/command.go
goagen/main.go
goagen/meta/generator.go

When running a gen command, capture and pass additional, arbitrary command line flags to the
final generator.  For example, given the following command
goagen --design=... gen --pkg-path=... -- --special=true -o test
The `--special=true -o test` flags will be passed to the final generator.

goagen: pass extra flags to gen plugins

---

design/types.go
design/types_test.go
goagen/gen_app/writers.go

This will make the generated code more stable, otherwise types like these would randomly switch positions each time `app` code was generated:
- `MyAppReferenceScope`
- `MyAppReferenceScopeLink`

ACL-214 MediaTypesWriter will iterate views in a consistent order

---

design/api.go
design/apidsl/response.go
design/apidsl/response_test.go
goagen/gen_app/writers.go

This PR makes it possible to define responses with "raw values" i.e. values that are not described by media types (not objects). For example `HashOf(String, Any)`. The design syntax for such responses is:
```go
Response(OK, Integer)
```
This defines a response whose body is an integer. Another more complete example would be:
```go
Response(OK, HashOf(String, Any), "vnd.application.enumerated", func() {
Status(200)
}
```
Where all the arguments but the first are optional. This example assumes the existence of a response template taking one argument (whose value here is `"vnd.application.enumerated"`).

Allow "raw value" responses

---

design/apidsl/media_type_test.go
design/definitions.go
design/types.go

Address issue #307, where `json.Marshal` cannot handle `map[interface{}]interface{}`. The change examines the key type from the `Hash` and create a `map` with builtin type if possible.

Create json parsable map type (builtin key) if possible

---

design/api.go
design/apidsl/api.go
design/apidsl/api_test.go
design/validation.go
doc.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
mux.go
mux_test.go

And generate code that sets up the service mux accordingly.
This PR makes it possible to do:
```go
var _ = API("foo", func() {
BasePath("/api/:version")
VersionParam("version")        // Path param used to specify targeted API version
VersionHeader("X-Api-Version") // Header used to specify targeted API version
VersionQuery("version")        // Querystring value used to specify targeted API version
...
})
```
Where the `VersionXXX` DSL functions may each appear 0 or more times and may take one or more argument(s). `goagen` then generates code that sets up the mux so it "just works".

Add DSL for defining param, header and querystring based versioning

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

This commit cleans up two small issues:
- Remove unnecessary int-to-int type conversions for Integer types.
- Return error from ctx.ResponseData.Write call in context response func.

goagen: clean up gen_app templates

---

.gitignore
design/api.go
design/apidsl/api.go
design/apidsl/media_type.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_main/generator.go
mux.go
service.go
service_test.go

Fix issues with "Reference": it now properly initializes the version
basic properties from the API's.

Properly generate version encoders.

---

design/apidsl/media_type_test.go
design/definitions.go
design/example.go
design/types.go

Issue #314 Fixes
* avoid OOM from creating a large slice in example because of high `MinLength`
* add `Any` type handling in both `Array` and `Hash` `GenerateExample`
* generate example with more precise type instead of using `interface{}` everywhere (make tests easier)

Fixes Issue #314: handle Any while generating examples

---

dslengine/runner.go
goagen/gen_app/generator.go

, and as a way to keep a `gen/main.go` (like the output of `goagen/meta`, but inside the
project).
The goal of having a `gen/main.go` is to ease team discovery, and to
more easily work on our own generators.
The goal is to make this work: https://gist.github.com/abourget/06c803e1e9e102f7dec4

Added `FailOnError` function, tohandle MultiError

---

design/types.go
goagen/codegen/types.go
goagen/codegen/workspace.go
goagen/gen_app/writers.go

This commit updates the descriptions for media type views and collections to
proper godoc formatting.
I had to import `codegen` to get access to `Goify`.

Generate proper media type godocs

---

design/api.go
design/api_test.go
design/apidsl/api.go
design/apidsl/api_test.go
design/definitions.go
design/validation.go
encoding.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_main/generator.go
goagen/gen_swagger/swagger_test.go
service_test.go

Replace factory interface with function which provides for
a much more lightweight extension point.
The DSL has been extended to provide the ability for
overridding the default encoder and decoder producing functions
(NewEncoder and NewDecoder respectively).
So that designer does not have to worry about
whether or not slash prefixes or trailing slashes
are required.

Encoding redux.

---

dslengine/runner.go

I'd like have a `gen/main.go` file like this:
```
package main
import (
_ "github.com/abourget/featurette/design"
"github.com/abourget/featurette/gensec"
"github.com/goadesign/goa/design"
"github.com/goadesign/goa/dslengine"
"github.com/goadesign/goa/goagen/gen_app"
"github.com/goadesign/goa/goagen/gen_swagger"
)
// Run with: "go run gen/main.go" from the root of your project.
func main() {
dslengine.FailOnError(dslengine.Errors)
dslengine.FailOnError(dslengine.Run())
genapp.TargetPackage = "app"
dslengine.PrintFilesOrFail(new(genapp.Generator).Generate(design.Design))
dslengine.PrintFilesOrFail(gensec.Generate("app"))
dslengine.PrintFilesOrFail(new(genswagger.Generator).Generate(design.Design))
}
```
These small fixes enable that.

Simplify a potential `gen/main.go` in project's files.

---

.gitignore
context.go
error.go
error_test.go
service.go

The usage is now as follows:
1. Create an error class, this returns a function
2. Use the function to create errors
3. Call `Meta` on the errors to add key/value pairs
The ErrorClass function accepts a format and values a la `Printf`.
The format may be any type which makes it simple to wrap "raw"
errors.

Change how ErrorClass works to allow for Key/Values

---

security.go

Fixes generated code for OAuth2Security.

Rename the `AuthenticationURL` to `AuthorizationURL` .. just got mixed up!

---

goagen/gen_app/writers.go

I have a panic error when i use jwt security without Security.Scopes in handleSecurity
I can change this type assertions or add scopes in context (line 732) even it empty

Fix security empty scopes panic

---

error_test.go
goagen/gen_main/generator.go
middleware/error_handler.go
middleware/error_handler_test.go
middleware/gzip/middleware_test.go
middleware/middleware_test.go
service.go
service_test.go

Replaces the service and controller error handlers.
This has several benefits, mainly it fixes a bug where error returned by
middlewares would not be caught because the error handler was at the
bottom of the middleware chain. Putting the error handler at the top of
the chain does not work with middlewares that rely on the HTTP response
being initialized like LogRequest.
Using a middleware allows the client code to control where the mapping
from error to HTTP response is done. The bootstrap code generated by
gen_main builds the middleware stack in the "right order" (i.e. the
error handler middleware is closer to the action handler then the
LogRequest middleware).

Introduce error handler middleware.

---

error.go
goagen/gen_main/generator.go
middleware/error_handler.go
middleware/error_handler_test.go
service.go

Also wrap file server handler with middleware so that for example
errors are properly logged.
Fix #357

Fix ServeFiles on "/index.html"

---

error.go
mux.go
service.go
service_test.go

Part of this commit involves making the middlewares service field
private to make sure middleware setup goes through Use which now
checks whether controllers are already mounted and panics if that's the
case. This serves two purposes:
1. It prevents registering middleware that won't actually take effect
because mounted after the middleware chain for a controller has been
computed.
2. It also prevents middleware to be registered after the middleware
chain for the "NotFound" handler has been computed.

Properly handler requests sent to unregistered paths.

---

logging.go

Use %#+v to log values in stlib logger adapter

---

context.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
logging.go
logging/kit/logger.go
logging/kit/logger_test.go
logging/log15/logger.go
logging/log15/logger_test.go
logging/logrus/logger.go
logging/logrus/logger_test.go
logging_test.go
middleware/log_request.go
middleware/middleware_test.go
service.go

To reflect better its usage. Add New method to the interface
which instantiates a new log adapter given a context. This
makes it possible to keep the log context inside the logger
instead of in the goa context. This in turns allows the
logger to be used more naturally in user code (extract
logger from context, assert against actualy logger type and
use as usual, context is initialized correctly).

Rename Logger interface into LogAdapter

---

goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

Both these can be used now:
```
cellar-cli list bottles /cellar/accounts/1/bottles --years=2012
cellar-cli list bottles --accountsID=1 --years=2012
```
To produce the following request:
```
GET /cellar/accounts/1/bottles?years=2012
```
The path takes precedence when specified.

Add ability to specify path parameters via flags in the client CLI.

---

design/definitions.go
design/types.go
design/types_test.go
goagen/gen_client/generator.go

Add UserTypes to ActionDefinition and ResourceDefinition.
This method returns the user types used by the respective targets recursively.

Properly generate user types required by client package.

---

design/apidsl/attribute.go
design/types.go

The bug affects media type attributes which themselves are attributes and
use the default view (don't have a view specified in the DSL). These are
not projected which produces incorrect validation code if the default
view attribute list differ from the media type attributes.

Correctly project media type attributes that use the default view.

---

design/apidsl/attribute_test.go
design/apidsl/type_test.go
design/random.go
design/types.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/codegen/workspace.go
goagen/gen_app/generator.go
goagen/gen_app/test_generator_test.go
goagen/gen_app/writers.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_schema/json_schema.go
validation.go
validation_test.go

This adds the functionality of handling UUID's as a primary key, in the routes, and payloads. This is to compliment the addition of uuid support as primary key in gorma. https://github.com/goadesign/gorma/pull/93
In addition, this fixes a small bug when removing imports. It will now properly call the right method for named and non-named imports.

Add UUID datatype.

---

design/apidsl/security.go
design/apidsl/security_test.go
design/security.go
design/security_test.go

Tweak security DSL comments and make scheme description optional.

Make it possible to use relative URLs for token and authorization OAuth2 URLs.

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

There is a slight risk of collision with `datatypes.go` but we'll cross
that bridge when we get there.

Remove `_client.go` suffix to files generated by `gen_client`.

---

design/definitions.go

Recursively traverse response media types for dependent media types that are
not directly used by responses

Properly generate media type dependencies in gen_client

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

So that it's possible to configure each signer properly from user code
without having to go through the command line.

Use concrete signer type in generated client fields

---

Makefile
goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

Use 'Signer' as a suffix rather than prefix.

---

goagen/gen_client/generator.go

To make it possible for client packages to build requests and potentially process them further before actually sending them.

Split action client methods into build and make request methods

---

middleware/error_handler.go
middleware/error_handler_test.go
service.go

- Go's `http.StatusText(500)` returns `"Internal Server Error"`

using http.StatusText(...) instead of "internal error"

---

goagen/codegen/types.go
goagen/gen_client/cli_generator.go
goagen/meta/generator.go

* Protect against "client" package and local variable names clash
* Default client CLI tool version to "0" if no version in API
* Sort flags used to spawn generator tool so generated header comments are deterministic.

Misc fixes:

---

middleware/request_id.go

Allows to choose another request id header, if necessary.
Generated code continues to use the standard header.

Generalize request id header

---

context.go
service.go

Instead use closures to lazily compute middleware chains.
This makes it possible to mount controllers and middlewares in any order.

Remove need for "finalizing" service.

---

goagen/gen_app/test_generator.go

`gen_app` generates some BadRequest test, but calling a BadRequest test with invalid payload causes panic.
This change is intended to pass tests with invalid payload when expected BadRequest.

Fix payload validations in app tests

---

goagen/codegen/finalizer.go
goagen/codegen/publicizer.go
goagen/codegen/validation.go

When a type has a field whose type is itself - which in case you are
wondering is a valid scenario :) (e.g. a "Person" type with a "friend"
attribute of type "Person").

Fix potential infinite recursions during codegen.

---

goagen/codegen/types.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/test_generator_test.go
goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_main/generator.go
goagen/main.go

Behaves identically to the `app` and `main` command flags with the same
name.
Also protect generated code against clashes between variable names and
target package name.

Add `--pkg` flag to `client` command.

---

design/apidsl/action.go
design/definitions.go
error.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go

```go
Action("Update", func() {
Payload(func() {
Member("id")
Required("id")
})
})
```
The above `Action` should return `400 Bad Request` when no payloads given.
This pull request implement that.

Return err when some payloads required but no payloads specified

---

design/apidsl/action_test.go
design/apidsl/media_type.go
design/apidsl/resource.go
design/apidsl/resource_test.go

When creating identifier since goa now supports arbitrary encodings.
Also properly keep media type modifiers when using `DefaultMedia`.

Remove special case for JSON media type.

---

service.go

the default `NotFound` implementation can mess up the JSON response, appending `"null\n"` to an otherwise good 404 string:
So the client would receive:
```json
{"code":"not_found","status":404,"detail":"/"}
null
```
instead of:
```json
{"code":"not_found","status":404,"detail":"/"}
```

fix improperly formatted responses due to "null\n" being appended

---

goagen/gen_app/writers.go

from `UseXXX` to `UseXXXMiddleware` where XXX is the name of the security scheme

Rename generated function that mounts security middleware

---

design/definitions.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

As Swagger does not support "exceptions". So if the API uses any
absolute route or file servers then set the BasePath to "" and use
absolute paths everywhere.

Only set API BasePath if all actions are relative to it.

---

goagen/gen_app/writers.go

Probably it is a slip of the keyboard.

Fix parging layout in application generation

---

README.md
_integration_tests/integration_test.go
client/signers.go
design/security.go
goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/main.go

This PR changes how the client tool is generated. The file `main.go` is now a scaffold meaning that it is generated once and does not get overridden with further invocations of `goagen client`. The code that creates the cli commands is moved from the `main` package to the new `cli` package so that it does get regenerated each time.
The file `main.go` thus becomes an example rather than an authoritative implementation of the client tool making it possible to change it for example to register custom auth signers. The `goa` package signers is also changed to a more generic implementation allowing for any implementation of the `JWT` or `OAuth2` security schemes to be plugged in. The interfaces used by the `JWT` and `OAuth2` signers is now compatible with the [golang …

Turn client tool info scaffold

---

.gitignore
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

That causes query string and header values to be set incorrectly
if their 'goified' name differs from their given name.

Fix bug in gen_client in generation of NewXXXRequest functions

---

client/signers.go
goagen/gen_client/cli_generator.go

Since it already defaults to sign using a bearer authentication value.

Change client API key signer to default to sign header.

---

design/apidsl/security.go
design/apidsl/security_test.go
design/security.go

Only use scheme defined in API if any. This means that relative URLs are
possible which is better than an incorrect URL because of default scheme
and no host.

Do not use default scheme when computing auth URLs

---

design/validation.go
goagen/codegen/types.go
goagen/codegen/types_test.go

Also fix validation of path that was erroneously taking into account
parent resource and API base paths for absolute routes.

Fix codegen issue with type descriptions containing newlines.

---

goagen/gen_app/test_generator_test.go
goagen/gen_client/generator.go
goagen/main.go

I have been finding myself using quite of bit of the helpers in the client library but not the tool itself. This adds the ability to prevent the generation of the tool and cli.

Allow the ability to generate no tool.

---

cors/cors.go
design/apidsl/api.go
goagen/gen_app/writers.go

So they get properly wrapped with the controller middleware.

Tweak CORS preflight handlers code generation

---

goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
service.go
service_test.go

Store unmarshaler error in context and handle it in generated code so
that middleware that is request specific such as CORS is properly
executed. This also simplifies the setup and makes the code easier to
evolve to the point where goa MuxHandlers do not return errors (for
compatibility with Go 1.7 HTTP handlers).

Refactor how payload is unmarshaled

---

design/apidsl/media_type.go
design/apidsl/media_type_test.go
design/types.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go

Instead of always using the media type identifier. In particular this
makes it possible to have different media types use the same value for
Content-Type. This also helps with APIs that must support multiple
encodings.

Add ability to set "Content-Type" response header explicitly.

---

goagen/codegen/helpers.go
goagen/codegen/version.go
goagen/codegen/workspace.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/test_generator_test.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_js/generator.go
goagen/gen_js/generator_test.go
goagen/gen_main/generator.go
goagen/gen_main/generator_test.go
goagen/gen_schema/generator.go
goagen/gen_schema/generator_test.go
goagen/gen_swagger/generator.go
goagen/main.go
goagen/meta/generator.go
version/version.go
version/version_suite_test.go
version/version_test.go

Generators now check whether the version of goa used to compile the
final code generation tool is compatible with the version used to
compile goagen itself.

Add proper versioning support to goagen

---

client/client.go
goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go

Use an interface instead of the http package `Client` struct so that
it's easier to mock and override the client `Do` method.

Introduce Doer interface

---

goagen/gen_app/test_generator.go

Test methods created by `goagen` return the result as pointer, but they should use pointer and non-pointer properly.

Fix return type in app tests

---

context.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Since it should only be used to access encoders.

Move service to response data in context.

---

goagen/gen_app/test_generator.go

Probably it is a typo.
before #570 
```
method := TestMethod{}
//snip...
method.ActionName = codegen.Goify(action.Name, true) // ← << true >>
//snip...
method.ContextVarName = fmt.Sprintf("%sCtx", codegen.Goify(action.Name, false)) // ← << false >>
```
#570 
```
actionName = codegen.Goify(action.Name, true) //← << true >>
//snip...
return &TestMethod{
Name:           fmt.Sprintf("%s%s%s%s%s", actionName, ctrlName, respQualifier, routeQualifier, viewQualifier),
ActionName:     actionName, // ← << true >>
ResourceName:   ctrlName,
Comment:        fmt.Sprintf("%s %s", actionName, comment),
Params:         params,
Payload:        payload,
ReturnType:     returnType,
ControllerName: fmt.Sprintf("%s.%sController", g.target, ctrlName),
ContextVarName: fmt.Sprintf("%sCtx", action.Name), // ← << …
```

Fix a bug of #570

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

This change makes it possible to set the service used by the test helpers to run the action.
Also it removes the `WithContext` variations to instead only have one helper generated by response that always accepts a context.
The helper takes care of initializing the context if a nil value is given.
It also initialized the service to a default test service if it is nil.

Make it possible to set service used by test helpers

---

goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

So that there is no clashes between names of commands.

Keep file extension when generating "Download" client method.

---

design/definitions.go
design/validation.go
goagen/gen_app/generator.go
goagen/gen_app/writers.go
goagen/gen_swagger/swagger.go
service.go

This PR makes a couple of changes to improve the overall support of Swagger:
1. It fixes an issue where file servers serving a directory do not
serve the file `index.html` for requests with a path that matches the
top level directory path. So for example a file server serving the
content of the directory `public` on `/swagger/*file` will now serve
`public/index.html` for requests to `/swagger/`.
2. Swagger paths are now tagged with the action resource name by default.
This can be overridden using the Metadata `swagger:tag:xxx`.
3. The paths summary are now built by concatenating the action and
resource names with a space in between. This can be overridden using
the metadata `swagger:summary:xxx`.

Improve overall Swagger support

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

This helps with looking up the file where an error happened since
`go test` only prints the file name and not the path thereby confusing
tools like vim-go when the file name matches the controller file name.

Change test filenames to add `_testing` suffix.

---

goagen/gen_main/generator.go

`goagen` generates `main.go` to serve with a port `8080`.
This patch makes it to use a port specified by `apidsl.Host()`.

Use a port specified by apidsl.Host() in gen_main

---

goagen/gen_app/test_generator.go

When a query string is a slice of strings

Fix issue with generated code in test generator

---

goagen/codegen/helpers.go

Why:
* When generating on Windows goagen puts goagen.exe into the output
causing different outputs on Windows vs Linux
This change addreses the need by:
* Stripping a possible `.exe` suffix from the calculation of the
command line. Crude, but simple

Remove .exe suffix from goagen output

---

goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/test_generator_test.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_js/generator.go
goagen/gen_js/generator_test.go
goagen/gen_main/generator.go
goagen/gen_main/generator_test.go
goagen/gen_schema/generator.go
goagen/gen_schema/generator_test.go
goagen/gen_swagger/generator.go

This makes it simple to re-run the bootstrap by simply doing
```
go generate
```

Add "go:generate" directive to generated "main.go"

---

goagen/codegen/workspace.go

So that it also works on Windows when the casing of e.g. the drive letter differs

Fix how goagen detects that a path is under GOPATH

---

goagen/gen_app/test_generator.go

`goagen` writes some fixed packages as import paths in app tests.
It should also include packages for types that used in `Params` and `QueryParams`.

Add imports in app tests

---

design/apidsl/media_type.go
design/definitions.go
design/security_test.go
design/types_test.go

When an attribute uses a collection on the media type itself such as:
```go
MediaType("application/vnd.menu+json", func() {
Attributes(func() {
Attribute("child", CollectionOf("application/vnd.menu"))
})
// ...
```

Properly handle cycles in media type definitions

---

design/security_test.go
design/types.go
goagen/gen_schema/json_schema.go

This PR fixes the Swagger generation so that the media types get properly projected prior to being rendered in the schema. Currently the code uses the "default" view. It may make sense to introduce metadata to control that behavior in the future.

Fix swagger generation of media type links.

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Instead of array with a single empty string item.
The flip side is that it's not possible to encode an array with a single empty string,
but that seems better than not being able to encode an empty array.

Create empty array when query string is empty.

---

middleware/request_id.go
middleware/request_id_test.go

added a default length limit of 128 for incoming X-Request-Id header values for safety
the issue is that request IDs will appear frequently in logs and the server could be impacted if a bad actor sends very long request IDs

request_id_length_limit

---

design/api.go
design/apidsl/init.go
design/apidsl/media_type_test.go
design/definitions.go
design/dup.go
design/example.go
design/types.go
goagen/gen_app/test_generator_test.go
goagen/gen_main/generator.go

So that code generators and finalizers (e.g. example finalizer) can rely on it.

Make sure projected media types define a default view

---

design/validation.go
goagen/gen_schema/generator_test.go
goagen/gen_schema/json_schema.go
goagen/gen_schema/json_schema_test.go

Also fixed issue where a MT attribute using a generated MT with a specific view would cause validation to fail. This is because the generated MT DSL has not been executed yet at this point. So moved that execution up to before the standard MT validation happens. This may need to get revisited as really the strong coupling between the two kinds of MTs means that generated MTs should probably not be a separate DSL root.

Fix potential panic due to using default view on MT without a default view

---

README.md

The strconv import did not exist. Adding it to the readme to make the walkthrough more clear.

Added missing import for step 3 of example

---

goagen/gen_app/test_generator.go

`gen_app` generates following comment.
```go
// CreateBottleCreated Create runs the method Create of the given controller with the given parameters and payload.
```
Maybe second word `Create` is unneeded.
```go
// CreateBottleCreated runs the method Create of the given controller with the given parameters and payload.
```
https://github.com/goadesign/goa-cellar/blob/f923c55476595a95fa4f97b03eb33b084fd9e58a/app/test/bottle_testing.go#L18

Fix a comment in app tests

---

design/apidsl/response.go
goagen/codegen/types.go
goagen/codegen/workspace.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

By using the struct metadata the designer can specify different names for headers and
params that have the same names. By default these end up creating a single struct
field with the common name.

Give designer the ability to choose how to handle headers and parameters with identical names

---

design/apidsl/action.go

in responses, actions and resources. This makes it possible to define
headers in traits and in these places as well. In case of conflict (same
header name) the last definition "wins".

Allow multiple Headers declaration

---

goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

Update client generator to generate all projected media types. The media types and user types are now generated in `media_types.go` and `user_types.go` respectively.

genclient: generate all projected media types

---

middleware/error_handler.go
middleware/error_handler_test.go

Copy original error ID in the error handler if not verbose. This ensures that the logged error ID matches what the client receives.

Copy original error ID in the error handler if not verbose

---

design/types.go
design/types_test.go

for example:
```go
View("default", func() {
Attribute("related_mt", func() {
View("tiny")
})
})
```
Prior to this change only views specified on media type attributes were
taken into account.

Use view attribute views

---

goagen/codegen/publicizer_test.go
goagen/codegen/types.go
goagen/codegen/types_test.go

`gen_app` generates struct tags for attributes in alpahbetical order when some `Metadata()` are specified, but it generates that in following order by default.
1. json
2. xml
3. form
Maybe they should be the same order.

Sort default attribute tags in alphabetical ordert

---

design/definitions.go
design/definitions_test.go

If the action did not define responses but the parent resource did.

Fix potential panic when finalizing action definitions

---

client/client.go
goagen/gen_client/cli_generator.go

This PR is for #646
BREAKING CHANGE - should be announced on #goa
- client.Doer.Do() takes a Context parameter
- existing callers that pass nil work as before
- existing callers that pass an http.Client instance need to wrap it using client.HTTPClientDoer
- existing callers that pass a custom Doer need to update the Do method in their impls to take the Context parameter

Add Context param to Doer.Do

---

design/types.go
goagen/gen_schema/json_schema.go

That's instead of the view used to project them so that projecting a
projected media type is idempotent (type name remains the same).

Change projected media types so they define the "default" view.

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

This makes it possible to iterate over all values defined in the design as being "parameters"
to the action including path parameters, query string parameters and now headers.
This PR also removes the previous behavior or splitting query params on commas to build slices.
Instead params must be passed in as actual arrays i.e. foo=bar&foo=baz. This makes it
possible to properly handle query strings such as foo=bar&foo=baz,abc which now result in the
Foo field being initialized with []string{"bar","baz,abc"} instead of
[]string{"bar","baz","abc"} as was done previously.

Set header values defined in design in request data Params map.

---

context.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Use the raw header name as key to be consistent with params.

Properly populate request data Params with header values.

---

goagen/codegen/workspace.go

Windows paths are case-insensitive.
goagen bootstrap failed because GOPATH was using different casing.

Fix path prefix check.

---

design/apidsl/media_type.go
design/apidsl/resource.go
design/apidsl/resource_test.go
design/apidsl/response.go
design/definitions.go
design/validation.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_main/generator.go

This PR makes it possible to specify which view to generate for a given response media type. If no view is specified then the structs corresponding to all views are generated (identical to the behavior prior to this PR). A view for a given response can be specified with:
```go
Response(OK, func() {
Media(BottleMedia, "tiny")
})
```
A view can also be specified for the default media type:
```go
Resource("bottle", func() {
DefaultMedia(BottleMedia, "default")
// ...
})
```

Media view

---

goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger_test.go

Sorry, Issue #659 was incomplete.
The same thing happens in the payload.

Fix gen_swagger not to omit payload validations of the zero value

---

encoding/json/encoding_suite_test.go
encoding/json/encoding_test.go
uuid/uuid.go

This is required by Client to parse Payload with UUID in it.

Add (Un)Marshal Text/Binary methods to support json parsing

---

encoding/json/encoding_suite_test.go
encoding/json/encoding_test.go
uuid/uuid.go

* Add (Un)Marshal Text/Binary methods to support json parsing
* Add tests and fix impl ;)
* Add local test setup. Add round trip test

Add (Un)Marshal Text/Binary methods to support json parsing (#670)

---

design/apidsl/action.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go

This commit does two things:
1. It makes sure that action definitions that refer to user types to
define the payload only duplicates the definition if needed (i.e. if
the payload definition overrides some of the type attributes).
2. It makes sure that a payload type is only generated if there is not
a user type with the same type name.

Fix potential duplicate generation of payload types.

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

Add each param to the url query string values instead of building comma separated string.

Properly handle array params

---

mux.go

This fixes an issue where requests sent by clients would not
match routes that contain characters that are escaped by the
net/url algorithm used to build URL strings. In particular
this affected routes with '*' in them.
See https://github.com/dimfeld/httptreemux/issues/32

Add escaped routes to mux.

---

design/definitions.go
design/dup.go
design/dup_test.go

This is so that if the type is a media type or user type then it's OK
if the DSL hasn't run yet. The DSL will run later initializing the
referred type. If we dupped then the dupped type DSL would never get
run and the media type would not have its views initialized for example.

Do not copy attribute type in DupAtt

---

error.go
service.go

So that it's possible to override it, e.g. for clients that can only handle
Content-Type headers of the form 'application/json'

Make ErrorMediaIdentifier a variable instead of a constant

---

design/apidsl/media_type.go
design/definitions.go
design/types.go
design/types_test.go
goagen/codegen/types.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers_test.go
goagen/gen_js/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/json_schema.go

Using the non default view. This PR cleans up how projected media types are handled:
A projected media type identifier now includes the view so that it's possible to infer
whether a media type has already been projected. Projected media types also only
define the "default" view.

Fix generation of examples for media types

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Even if it's invalid so that its content can be logged properly

Always initialize request payload

---

README.md

Signed-off-by: Shoubhik <shoubhik@dhcp35-156.lab.eng.blr.redhat.com>
WHY:
The documentation is good and helps - and removing typos make it easier.
WHAT:
Fixed the typo "no" to "not"

#709 fixed readme typo

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go
goagen/gen_app/writers_test.go

The generated test helper code would sometimes call Validate()
on media types that did not define it because the test was being
made against the private MT data structure instead of the public one.

Fix spurious call to Validate() in test helpers

---

design/types.go

Attributes may have nil types temporarily as the DSL executes.

Protect IsCompatible against attributes with nil types.

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

The header Access-Control-Allow-Origin doesn't accept
wildcards such as *.example.com. Therefore after the
origin has been checked as valid, the header should
contain the origin without wildcards.
For example if we got an origin such as test.example.com
and we accept origins matching *.example.com, the resulting
header will be: Access-Control-Allow-Origin: test.example.com
Fix #711 
Signed-off-by: Matteo Suppo <matteo.suppo@gmail.com>

Generate cors headers without wildcards

---

goagen/gen_app/test_generator.go

So that further checks don't panic.

Fail test fatally if media type is not of the right type

---

cors/cors.go
cors/cors_test.go
design/apidsl/api.go
design/definitions.go
design/validation.go
goagen/gen_app/generator.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

If the string passed into Origin() begins and ends with a "/"
it's considered a regular expression.
For example "/[api|swagger].goa.design/" can match both
api.goa.design and swagger.goa.design
Fix #718
Signed-off-by: Matteo Suppo <matteo.suppo@gmail.com>

Allow cors spec to be defined as regexps

---

goagen/gen_app/writers.go

Fixes #694.
`ContentType` wasn't applied, instead, the `MediaType` identifier was used.

Fix ContentType isn't applied in MediaType (#694)

---

logging.go

- logit() doesn't need to modify `a.keyvals` because it was already fixed up in New()

goa.adapter#logit(): remove unneeded check which would make an unsafe concurrent modification

---

goagen/gen_client/generator.go

This is a trivial change.
```go
if bar != nil { 
header.Set("foo", *bar) 
}
```
```go
if bar != nil { 
header.Set("foo", *bar) 
}
```

Fix gen_clinet to suppress blank lines

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/generator.go
goagen/gen_client/generator.go

Fix length validations to count the length of the string using by utf8.RuneCountInString().

---

error.go
error_test.go

Fix #743 
Make InvalidRangeError accept `interface{}` for the type of the value so that it works correctly both for `int` and `float64` values.

Properly handle float range errors

---

design/apidsl/attribute_test.go
design/types.go
goagen/codegen/finalizer.go
goagen/codegen/finalizer_test.go

Fix setting a default value to datetime

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

This is an API definition.
```go
var _ = apidsl.API("An API", func() {
apidsl.Metadata("swagger:tag:Backend")
apidsl.Metadata("struct:tag:json", "myName,omitempty")
apidsl.Metadata("swagger:gat:dnekcaB")
```
`gen_swagger` generates following swagger.yaml (and json).
```yaml
tags:
name: Backend
name: json
name: dnekcaB
```
But valid tag is only top so it should be outputs only that.
```yaml
tags:
name: Backend
```

Fix to contain only valid tags in gen_swagger

---

design/apidsl/action.go
design/apidsl/action_test.go
design/apidsl/metadata.go
design/apidsl/metadata_test.go
design/definitions.go
design/security.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

This pull request extends `apidsl.Metadata()` to support [Swagger Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md).
Now it includes only core implementations so I will add tests and comments for godoc.
https://gophers.slack.com/archives/goa/p1473747445000640

Support swagger extensions

---

metrics.go
metrics_test.go
service.go

* Add function for normalizing metric keys
* Add tests for metrics functions.

Modify metrics so that names are normalized to legal chars

---

middleware/error_handler.go
middleware/error_handler_test.go

@raphael  This is a pass at the changes I proposed for issue-781 https://github.com/goadesign/goa/issues/781
One concern I have here is backwards compatibility. If users are relying on type checks for errors they will stop working.
For example if they were relying on checks like
```
if err, ok := err.(goa.ServiceError); ok {
}
```
From a usability point of view there is no difference however. A user of goa can still do something like
```
return goa.ErrInternal("something strange")
```
and it will work as expected except now you will see a trace in the logs

make a pass at the changes for implementing issue-781 integrating pkg/errors

---

design/types.go
design/types_test.go

Handle media type attributes called 'links' properly

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Instead of just nil so that client can differentiate if
encoding allows.
Fix #809

Write empty collection if value is nil

---

design/apidsl/api.go
design/apidsl/api_test.go

Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

Change UseTrait APIDSL function to be variadic

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

https://github.com/goadesign/goa/blob/master/goagen/gen_swagger/swagger.go#L882
```go
if action.Payload != nil {
payloadSchema := genschema.TypeSchema(api, action.Payload)
pp := &Parameter{
Name:        "payload",
In:          "body",
Description: action.Payload.Description,
Required:    true,            // ←★ always true even if optional payloads be used.
Schema:      payloadSchema,
}
params = append(params, pp)
}
```

Fix a bug that the payload is always required 'true' in swagger documents.

---

middleware/security/jwt/context.go
middleware/security/jwt/error.go
middleware/security/jwt/jwt.go
middleware/security/jwt/jwt_test.go
middleware/security/jwt/resolver.go

To introduce new "simple" resolver.

Refactor JWT key resolver

---

service.go

Hi.
I very often use unix domain socket listener with HTTP proxy server. (e.g, Nginx)
In goa, it looks no way to use that.
This p-r add function `service.ListenAndServeUnix` that support unix domain socket listener.
Can you review this?
Thank you.

Add unix domain socket listener to service.ListenAndServeUnix

---

design/dsl/metadata.go
design/dsl/metadata_test.go
design/endpoint.go

@raphael I have made a first attempt at adding a test for the metadata dsl function. It needs expanding on with more types that can have ```MetadataExpr``` but I wanted to show what was here to allow for feedback before I went too far.
Some questions from me:
1) Are we ok using a separate package as in ```dsl_test``` I think that this allows for clearer testing of the api
2) I believe I have understood how these tests work however I am quite new to the internals of goa, so it is possible I am misunderstanding something.

add metadata dsl test. Initial pass for feedback

---

design/apidsl/metadata.go
design/definitions.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

Can be applied to resources, actions and file servers.
Set the value to "false" to prevent Swagger specification from being generated. Example:
Resource("invisible", func() {
Metadata("swagger:generate", "false")
Action("visible", func() {
Metadata("swagger:generate", "true") // Override resource swagger:generate metadata
})
})
Fix #628

Implement "swagger:generate" metadata

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

…nd multiple parameters, instead of a single parameter separated by comma

swagger ui fails to send a proper request when a paramter is Arrayof(...)

---

design/apidsl/type.go
design/apidsl/type_test.go
goagen/codegen/validation.go

To make it possible to define validation rules on the array element. For example:
var Names = ArrayOf(String, func() {
Pattern("[a-zA-Z]+")
})
Fix #552

Add DSL argument to ArrayOf

---

goagen/gen_client/generator.go

That is only if API supports multiple inbound content types.
Fix #881

Only generate "contentType" argument for clent methods when necessary

---

goagen/gen_app/test_generator.go

So that only tests for responses that return ErrorMedia do not fail and others compile.
Fix #883

Fix payload validation handling in tests

---

goagen/gen_schema/json_schema.go
goagen/gen_schema/json_schema_test.go

Swagger definitions reference not working from updaged latest goa .
maybe ref #878

fix unlinked reference

---

goagen/gen_client/generator.go

We are using the v1 branch and lately there seems to be a change about the `contentType` parameter. I've commented on the recent commit [here](https://github.com/goadesign/goa/commit/2e83b0dfdd45e1e54615606924dca565b547b08b#commitcomment-19905560). 
This change removes the parameter `contentType` parameter from a function call under the same conditions as introduced in 2e83b0dfdd45e1e54615606924dca565b547b08b.
Also, I've added a workaround to remove the `header declared and not used error` which was caused because no content type is being anymore.

Fixup for 2e83b0dfdd45e1e54615606924dca565b547b08b

---

goagen/gen_client/generator.go

* Fixup for 2e83b0dfdd45e1e54615606924dca565b547b08b
We are using the v1 branch and lately there seems to be a change about the `contentType` parameter. I've commented on the recent commit [here](https://github.com/goadesign/goa/commit/2e83b0dfdd45e1e54615606924dca565b547b08b#commitcomment-19905560). 
This change removes the parameter `contentType` parameter from a function call under the same conditions as introduced in 2e83b0dfdd45e1e54615606924dca565b547b08b.
Also, I've added a workaround to remove the `header declared and not used error` which was caused because no content type is being anymore.
* Create header if .HasPayload .HasMultiContent 
See https://github.com/goadesign/goa/pull/900#pullrequestreview-9501415 for change request.

Backport for #900

---

goagen/gen_app/writers.go

This way CORS headers are properly returned even if security
check fails (e.g. session expired)
Fix #886

Handle CORS first, then security middleware

---

goagen/gen_schema/json_schema.go
goagen/gen_schema/json_schema_test.go

Since the names are different for media type projected to different
views anyway.

Revert to using type names for Swagger schema IDs

---

middleware/log_request.go

Log request HTTP headers in LogRequest middleware

---

goagen/gen_client/cli_generator.go

This argument does not exist if the API only supports one input content type
Fix #908

Remove extraneous contentType argument in command method call

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

When validating arrays. Only call Validate if the array element type
defines validations

Corretly call Validate on user type attributes

---

goagen/codegen/types.go
goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger_test.go

This PR fixes an issue where a response defined with a media type such as:
Media(Collection(Other), "view")
would cause the generated Swagger to lack the corresponding schema definition.
Fix #935

Properly generate Swagger for collection media type views

---

goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go

in the CLI code. Query string parameters are already escaped properly.
Fix #944

Make sure to escape path parameters when building request URL

---

goagen/main.go
goagen/meta/generator.go
goagen/meta/generator_test.go

This change will allow arguments to goagen which are add after the '--' argument to be passed allong to the generator.
The generate command becomes goagen gen -d <design> --pkg-path=<generator> -- --custom-arg=value
Fixes #934

Pass arguments to final generator

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

When the conversion of the header value to string requires multiple lines such
as when it is a UUID.
Fix #958

Fix code that sets request headers in client package

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/generator.go
goagen/gen_client/generator.go

Checking the difference of v1.1.0, I noticed that #740 is not backporting to the v1 branch.

Fix the generation of length validation for strings that contain multi-byte UTF-8 characters.

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

( if param is DateTypeKind ). This PR should be fixing bug I reported in #961.

Path generation in client should contain RFC3339 formatted time

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

I have a feeling that it could be done with a bit less duplicity within `initParams`. Opened to any ideas (or just push a change) :).
PR is fixing issue #961, which was partially fixed yesterday.

Generating path for client is transforming all relevant types to string first.

---

design/apidsl/action.go
design/apidsl/resource_test.go

Using `Metadata(''swagger:generate", "true")` in `Resource()` cases panic.
```
$ goagen app -d cellar/design
exit status 2
panic: assignment to entry in nil map
goroutine 1 [running]:
panic(0x39bd20, 0xc420169e10)
/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/goadesign/goa/design.(*ResourceDefinition).Finalize.func2(0xc4201b8280, 0xc4201af260, 0x401402)
/Users/ikawaha/go/src/github.com/goadesign/goa/design/definitions.go:848 +0x10b
github.com/goadesign/goa/design.(*ResourceDefinition).IterateActions(0xc42017e2a0, 0xc4201f9bf8, 0x0, 0x0)
/Users/ikawaha/go/src/github.com/goadesign/goa/design/definitions.go:682 +0x1d8
github.com/goadesign/goa/design.(*ResourceDefinition).Finalize(0xc42017e2a0)
/Users/ikawaha/go/src/github.com/goadesign/goa/design/definitions.go …
```

Fix potential panic when finalizing resource definitions

---

client/client.go
client/client_suite_test.go
client/client_test.go

@raphael added client.SetContextRequestID() to allow for sending a custom "X-Request-Id" header with client requests
added client/*_test.go files

support_custom_request_id_in_client

---

client/client.go
client/client_suite_test.go
client/client_test.go

@raphael added client.SetContextRequestID() to allow for sending a custom "X-Request-Id" header with client requests
added client/*_test.go files

support_custom_request_id_in_client_master

---

goagen/gen_client/cli_generator_test.go

This should do the trick, but I don't have access to a windows machine at the moment to test it myself.

Fix cli generator test by accounting for os seperators.

---

Makefile
middleware/context.go
middleware/tracer.go
middleware/tracer_test.go
middleware/xray/client.go
middleware/xray/middleware.go
middleware/xray/middleware_test.go
middleware/xray/segment.go
middleware/xray/segment_test.go

The Tracer middleware retrieves the trace ID and parent span ID from the
incoming request if present and stores the in the context. The middleware
provides a goa Doer wrapper function that extract the values from the context
and sets them in the outgoing request.
The middleware constructor accepts a percentage as argument which specifies the
sampling value. This value is used when the incoming request does *not* include
tracing headers to determine whether a new trace ID should be computed and set
in the context.
The xray middleware leverages the values set in the context by the Tracer
middleware to report tracing information to the AWS X-Ray service. The package
also makes it possible to attach further information to the traces such as
annotations and metadata. The middleware also …

Add Tracer and AWS X-Ray middlewares.

---

goagen/gen_app/test_generator.go

This allows github.com/pkg/errors wrapped errors to return their full stacktrace instead of just the error message

Use %+v instead of %s for errors

---

goagen/gen_app/test_generator.go

Identical to previous PR, but on the v1 branch
This allows github.com/pkg/errors wrapped errors to return their full stacktrace instead of just the error message

v1: Use %+v instead of %s for errors

---

goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/test_generator.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
service_test.go

So that if a middleware changed the request object (e.g. to change its context)
the new request object is handed over to the controller code.

Reset the http Request in the context in the generated handler.

---

middleware/xray/client.go
middleware/xray/middleware.go
middleware/xray/middleware_test.go
middleware/xray/segment.go
middleware/xray/segment_test.go

So it can be used by code that does not rely on the
middleware to report errors.

Make X-Ray segment RecordError method public

---

goagen/codegen/finalizer.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

This would close #754 (already closed) and half finish #658. I may set some time aside to cherry pick the changes for headers as well. I want to get this PR finalized and merged before that.
I made `codegen.printVals` public for use of printing the literal default values.
I added a lot of tests to make sure it was being handled properly everywhere. I may have gone a bit overboard.

Assign to default param values.

---

goagen/codegen/helpers.go
goagen/codegen/helpers_test.go
goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go

Related to this issues: https://github.com/goadesign/goa/issues/1035
@raphael Please, have a look! I made some initial changes that works in my branch. But I believe I might miss stuff. Also, I was thinking to pass a different parameter into the map instead of modifying the `Parent.Name` property.
ping @raphael

gen_cli: Replace underscores by dashes for the generated cmd arguments

---

goagen/gen_controller/generator.go

So that the default behavior matches the `main` and `bootstrap` commands.

Use "main" as default controller package name

---

goagen/gen_client/generator.go
goagen/gen_controller/generator.go
goagen/gen_js/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/generator.go
goagen/gen_swagger/generator.go

Generators in goagen except gen_app call panic when API definition is missing.
This patch fixes it.

Fix goagen to not call panic when API definition is missing

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

https://github.com/goadesign/goa/commit/0e7563b1eace965bb172548f8bf3174aa45e8370 adds a test context to reproduce the issue.
Then, https://github.com/goadesign/goa/commit/14b0f8d977ee9bd590e90b9c93c5302b61befdac is a patch to fix it.

Fix gen_client to not crash when an array parameter is defined in an action using websocket

---

cmd/goagen/generator.go
cmd/goagen/main.go
codegen/file.go
codegen/funcs.go

This patch fixes some renamed packages and functions, and change goagen's package to `main`.

v2:  Fix goagen to buildable

---

goagen/codegen/finalizer.go

When same user type is used to define different attributes at different "depth"
of parent type.
Fix #1016

Fix incorrect finalizer code.

---

goagen/codegen/publicizer.go
goagen/codegen/publicizer_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Add nil check for user type in gen_app

---

dsl/endpoint_test.go

@raphael Expanding on your test. Is the goal to achieve having one of these tests for each type of expression that makes up an endpoint rather than build up and duplicate? In my test I did not add a description as this was already tested in a previous test. 
Or is the goal to build up to a full example by adding to it piece by piece? In which case I should add a description attribute to my test. 
Another option here would be to have individual tests for each expression and then have a single test that pulls all of it together. This may work well as we are using maps for the test cases so have no certainty on execution order.

add payload test to endpoint_test

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Avoid using keywords for arguments in TestHelpers

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Avoid using variables name same with arguments in TestHelpers.

Avoid using keywords for arguments in TestHelpers (#1084)

---

design/apidsl/attribute.go
dslengine/runner.go

Make sure that reference type attributes have been computed
prior to building base attribute that relies on it.
Fix #1091

Fix Reference

---

middleware/security/jwt/resolver.go

If I understand the other documentation correctly, `Keys` can be `[]*ecdsa.PublicKey` too.

Keys allows []*ecdsa.PublicKey

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

That is when the set of mime types corresponding to the operation
responses differs from the overall API 'Produces' set.

Generate Produces on operations when necessary

---

goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Fix #1125
Signed-off-by: Matteo Suppo matteo.suppo@gmail.com

Generate tests correctly when headers are defined only on resource

---

middleware/tracer.go

Do it at call time so that the same traced doer can be reused to do many
requests potentially concurrently.

Fix TraceDoer so it fetches the trace details properly.

---

codegen/files/rest/paths.go

Mainly to make sure that names of generated functions are valid Go identifiers.

Make another pass at the paths file.

---

goagen/gen_client/cli_generator.go

Fix #1146.
This seems a regression by #1039.

Use kebak-case for resource names in gen_client

---

metrics.go
metrics_appengine.go

for https://github.com/armon/go-metrics/pull/47
goa uses packages not permitted by GAE of GCP PaaS and can not be used on GAE.
This can be solved by not including syscall containing the code of the package in question in the compilation.
I like Gore, so I would like to use it on GAE. So I requested it.
There is a problem with the dependency package, but if it is solved by goa it will be usable, so please consider.

Fix problem not starting with appengine

---

goagen/gen_client/cli_generator.go

Use kebab-case for resource names in gen_client (#1147)

---

goagen/codegen/finalizer.go
goagen/codegen/finalizer_test.go
goagen/gen_app/writers_test.go

Fixed func PrintVal in goagen/codegen/finalizer.go that returns int value string when setting zero as a default value to Number type.

Fix setting a default value to Number

---

error.go

Properly handle range error where the range limits are floats.

---

goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Instead of the goified version. This is so that the names appearing in the logs
reflect the design. This also helps with other types of instrumentation (e.g.
Prometheus graph names).

Store exact design action name in request context ContextAction

---

codegen/files/endpoint.go
codegen/files/endpoint_test.go

#1077.
This is a fix the generated codes to match the example.

Use new to initialize variables in endpoint writer

---

design/apidsl/action.go
design/apidsl/api.go
design/apidsl/attribute.go
design/apidsl/media_type.go
design/apidsl/metadata.go
design/apidsl/resource.go
design/apidsl/response.go
design/apidsl/security.go
design/apidsl/type.go

Some things I was unsure about so I noted them with a TODO. I will change them and resubmit if there is extra feedback...
Todos are on the following lines so far:
```
Desktop/goa/design/apidsl/api.go|154 col 4| // TODO: check if origin can really be used in action
Desktop/goa/design/apidsl/api.go|259 col 4| // TODO: can it really be used in Resource (no examples in docs)
Desktop/goa/design/apidsl/api.go|310 col 4| // TODO: can it really be used in Resource (no examples)
Desktop/goa/design/apidsl/api.go|437 col 4| // TODO: where is function used?
Desktop/goa/design/apidsl/media_type.go|367 col 4| // TODO: is this correct?
Desktop/goa/design/apidsl/security.go|310 col 4| // TODO: is this correct?
Desktop/goa/design/apidsl/type.go|8 col 4| // TODO: are these correct? They can be used as …
```

Added "can be used in" to the top of all DSL's

---

design/apidsl/media_type.go
design/apidsl/media_type_test.go

It makes it possible to specify the collection identifier.

Add an argument to CollectionOf()

---

goagen/gen_swagger/swagger.go

Currently the "produces" section is generated non-deterministically.
For example, sometimes like this:
```yaml
produces:
- application/vnd.goa.error
- application/vnd.my.object+json
```
...sometimes in another order:
```yaml
produces:
- application/vnd.my.object+json
- application/vnd.goa.error
```
This change preserves the order of the elements provided by `action.IterateResponses`.

sort the "produces" section of the swagger.yaml, swagger.json

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

So that the canonical key is used instead of the attribute name.
Fix #1242

Fix how headers are retrieved to build test context

---

goagen/gen_controller/generator.go
goagen/gen_controller/generator_test.go
goagen/gen_controller/options.go
goagen/gen_main/generator.go
goagen/gen_main/generator_test.go
goagen/gen_main/options.go
goagen/main.go

Add `--regen` goagen flag for `main` and `controller` commands.

examples/code_regen, but built in to goagen (#1246)

---

middleware/xray/middleware.go
middleware/xray/middleware_test.go

A `v1` companion to: https://github.com/goadesign/goa/pull/1254
> xray middleware to periodically redial daemon address because the IP address may change over time.

xray middleware to periodically redial daemon address

---

error.go

Fix was made in master: https://github.com/goadesign/goa/pull/995/commits/c1b4710773873f1f601439e5da36e759f4c77a71
But one line got skipped in the v1 backport: https://github.com/goadesign/goa/pull/996/commits/880f06fe697caf43ccc78797688949573c31552a

Bring grammar fix into v1.

---

logging/logrus/adapter.go
logging/logrus/adapter_test.go

Recently Sirpsen/logrus renamed to sirpsen/logrus. 
According to READ.me of sirpsen/logrus, I fixed the import path of logrus.
refs https://github.com/sirupsen/logrus

update logrus import path

---

goagen/main.go

It should be `main`. https://github.com/goadesign/goa/pull/1048

Fix default package name for gen_controller

---

design/definitions.go
design/definitions_test.go

Resources without a parent may be parents of other resources. For
deeper levels of nesting this is a problem.
E.g. Z -> Y -> X isn't sorted properly, but X needs to be processed first.

Process resource without a parent first

---

design/definitions.go
design/definitions_test.go

* Process resource without a parent first
Resources without a parent may be parents of other resources. For
deeper levels of nesting this can be a problem.
* Iterate over every previous element to ensure no parent was missed

Backport to v1: Process resource without a parent first (#1282)

---

service.go
service_test.go

goa can serve static assets via the DSL `Files` but it always uses the native file system. This patch makes it possible to use another `FileSystem` for that.

Changeable FileSystem for FileHandler

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

`HashOf` accepts optional DSLs as third and fourth argument which allows providing validations for the keys and values of the hash. But there is no validation codes generated.
**Sample design:**
```go
package design
import (
. "github.com/goadesign/goa/design"
. "github.com/goadesign/goa/design/apidsl"
)
var _ = API("cellar", func() {
Title("The virtual wine cellar")
Description("A simple goa service")
Scheme("http")
Host("localhost:8080")
})
var Bottle = Type("bottle", func() {
Param("names", ArrayOf(String, func() {
Pattern("[a-zA-Z]+")
}))
Param("bottles", HashOf(String, String, func() {
Pattern("[a-zA-Z]+")
}, func() {
Pattern("[0-9]+")
}), func() {
MinLength(1)
})
})
var _ = Resource("bottle", func() {
BasePath("/bottles")
DefaultMedia(BottleMedia)
Action("show", func() { …
```

Fix to generate validations of hash elements

---

goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go
goagen/gen_swagger/generator.go

Some generators just ignore the flag but they must still define it so that bootstrap can use it.
Fixes #1308

Fix bootstrap pkg, tooldir and regen flag

---

design/types.go
design/types_test.go

Make sure to generate strings when generating UUID examples.

---

design/definitions.go

Properly record error responses defined in resources or APIs

---

context.go
context_test.go

From documentation of net/http.ResponseWriter.Write
If WriteHeader has not yet been called, Write calls
WriteHeader(http.StatusOK) before writing the data.
Without this fix, ResponseData which went through middleware which depends
on documented behavior of net/http.ResponseWriter.Write, basically which doesn't
call net/http.ResponseWriter.WriteHeader explicitly, ended in non Written
state. This leads into situation that NotFound handler will write into
ResponseData although middleware did the write already.

Fix ResponseData.Write behavior to match net/http.ResponseWriter.Write.

---

error.go
error_test.go

This provides the interface for merging custom error response structs.
Tests and documentation to come after review of approach.

Add ability to customize errors response structure.

---

context.go
context_test.go

Same as #1325 but into v1 branch.

v1: Fix ResponseData.Write behavior to match net/http.ResponseWriter.Write.

---

goagen/gen_app/writers.go

Instead of setting the context to response set it to request.
This works because only request types are validated automatically.
Fix #1324

Fix validation error message when validating user types.

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

So that large integer values don't get formatted using exponential notation.
Fix #1327

Format values generated for min/max validations.

---

goagen/codegen/finalizer.go
goagen/codegen/finalizer_test.go

So that this is legal:
Param("num", Number, func() {
Default(50)
})
Fix #1342

Properly handle Number default values defined as int.

---

middleware/xray/middleware.go
middleware/xray/middleware_test.go

This was causing an X-Ray trace through multiple services to show up as a tree of subsegments under a single service. So queries like `service("xyz")` wouldn't show anything, even though the trace did flow through that service.

DMO-1294 xray: request-level segment shouldn't be marked "subsegment"

---

middleware/security/jwt/jwt.go

Fix the example in the documentation by asserting the claims type and adding a missing return nil at the end.

doc: Fix JWT validation handler example

---

design/random.go

So that example values stay the same no matter where `goagen` is run.
Fix #1353

Generate DateTime examples using UTC.

---

middleware/gzip/middleware.go
middleware/gzip/middleware_test.go

Change gzip middleware to only be employed if:
* Response is above specified size (Default: 256 bytes)
* Status code is one of. (Default: OK, Created, Accepted)
* Content type has one of X prefixes. (Default: Common types+ all `application/vnd.`)
Options added are `AddContentTypes`, `OnlyContentTypes`, `AddStatusCodes`, `OnlyStatusCodes` and `MinSize`.
Expanded tests to cover these.
In writing this I came across [this check](https://github.com/goadesign/goa/blob/master/middleware/gzip/middleware.go#L68) which I cannot find the reason behind. So if `"Content-Encoding"` header is set to `"gzip"` on the *request*, we will not use gzip? I have left it, but it seems like an odd check to have.

Improve gzip middleware

---

middleware/gzip/middleware.go

So that the defaults cannot be modified.

Do not use global variable to store default options

---

error.go
error_test.go
mux.go
mux_test.go
service.go
service_test.go

This PR changes the the way how goa handles not existent HTTP methods on existing endpoints and resolve #1372.
The new public `HandleMethodNotAllowed` is able to take a self defined handler. Therefore it was necessary to introduce a new `MethodNotAllowedHandler` which extends the the `MuxHandler` arguments by `map[string]httptreemux.HandlerFunc`. This allows to retrieve the allowed methods and handler by the MethodNotAllowed handler.
A default handler is included, which sets the appropriate status code, `Allow` header and a new error class.
This changes can be breaking in some edge cases, but introduce the correct behaviour described in https://tools.ietf.org/html/rfc7231#section-6.5.5

Added Method Not Allowed default handler

---

encoding.go
encoding/gogoprotobuf/encoding.go
goagen/gen_app/writers.go
goagen/gen_client/generator.go
middleware/gzip/middleware.go
middleware/gzip/middleware_test.go
service.go

* Need to buffer gzip content to compute proper content length
* Do not write headers prior to compressing so that content type and content
encoding headers can be written properly.

Fix gzip middleware so that headers are written properly.

---

middleware/gzip/middleware.go
middleware/gzip/middleware_test.go

I have tried to re-enable the unbuffered writes, so gzipped content doesn't have to be buffered. The problem before was that headers could be written after bytes had been written. This should no longer be possible. "Content-Length" is optional, so unless we already have it by accident, we just keep it out.
I have also made an option to Disable "Range" requests since they are unclear in compressed context. This includes removing the "Accept-Ranges" header on responses.
I have added an option if users would prefer "Range" requests to go through but disable compression instead.

gzip middleware updates

---

middleware/security/jwt/jwt.go
middleware/security/jwt/jwt_test.go

Allow JWT scopes claim to be named 'scope' or 'scopes'

---

goagen/utils/signal_appengine.go
goagen/utils/signal_lin.go

Syscall package does't permission on appengine.So, I fix it.
```
ERROR    2017-10-03 08:43:17,275 go_runtime.py:194] Failed to build Go application: (Executed command: /Users/jumpei/go_appengine/goroot-1.8/bin/go-app-builder -app_base /Users/jumpei/go/src/github.com/pei0804/hoge/server -arch 6 -dynamic -goroot /Users/jumpei/go_appengine/goroot-1.8 -gopath /Users/jumpei/go -nobuild_files ^^$ -incremental_rebuild -unsafe -print_extras_hash main.go)
2017/10/03 17:43:17 go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/goadesign/goa/goagen/utils/signal.go from GOPATH
```
[The App Engine SDK and workspaces (GOPATH) - The Go Blog](https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath)

Fix Correspondence of packages to be should excluded on appengine

---

cmd/goa/main.go

Now `goa` prints an error without a newline. The next prompt is printed to the same line like below.
```console
$ goa gen adder
no buildable Go source files in adder  $ 
```
This patch append a newline to the errors from `goa`.
```console
$ goa gen adder
no buildable Go source files in adder
$ 
```

Append a newline to the errors from goa

---

goagen/gen_app/generator_test.go
goagen/gen_app/writers.go

Discussed in #1396 
This change avoids modifying the response Content-Type if it has already been set.

goagen/gen_app: don't change Content-Type if already set

---

goagen/gen_app/generator_test.go
goagen/gen_app/writers.go

Backports https://github.com/goadesign/goa/commit/af615d5c3a6f02fb14b0952343cadcb2e6c5dabf to v1 branch, as requested in #1440.

goagen/gen_app: don't change Content-Type if already set (v1)

---

design/apidsl/api.go

Description can be added to almost anything (not sure how to describe secirity, docs and fileserver definitians)
Actually when I tried to open generated swagger in the online swagger editor (https://editor.swagger.io/) it complained that Response should have Description. And it was not mentioned in the docs that Description can be inside ResponseTemplate yet it indeed worked so I decided this help should be updated. :)

Update help for Description function

---

metrics.go

Instead of running go-metrics, we dump metric collection earlier.
This also allows overriding go-metrics with a compatible collector.
Backwards compatible, so we keep the NoOpSink and associated stuff.
Only overhead to "no" metrics is key normalization.
We have to use a mutex since atomic values cannot contain interfaces.

Completely bypass metrics

---

middleware/xray/wrap_doer.go
middleware/xray/wrap_doer_test.go

This way, the `middleware.TraceDoer` will include the latest span ID in the headers of the outgoing request.
Otherwise, the X-Ray service map would misrepresent a single request from A to B as two outgoing requests:
- `A` -> `B(client-side span)`
- `A` -> `B`
Now the service map will represent the single request as:
- `A` -> `B`

fix xray.WrapDoer to update segment in the context

---

middleware/xray/wrap_doer.go
middleware/xray/wrap_doer_test.go

(This is a `v1` companion PR to https://github.com/goadesign/goa/pull/1480)
This way, the `middleware.TraceDoer` will include the latest span ID in the headers of the outgoing request.
Otherwise, the X-Ray service map would misrepresent a single request from A to B as two outgoing requests:
- `A` -> `B(client-side span)`
- `A` -> `B`
Now the service map will represent the single request as:
- `A` -> `B`

fix xray.WrapDoer to update segment in the context (v1)

---

goagen/gen_app/writers.go

The code checking for presence of validation to know whether to generate a call to the payload 'Validate' method wasn't taking into account the case where the type only had required attribute validations.
Fix #1507

Properly test for required attributes when unmarshaling

---

design/example.go
design/example_test.go

Limit length of generated regular expression examples

---

codegen/service/service_data.go
codegen/service/service_test.go
design/method.go
http/codegen/server_error_encoder_test.go
http/codegen/testdata/error_encoder_code.go
http/codegen/testdata/error_response_dsls.go
http/design/endpoint.go
http/design/response.go
http/dsl/response.go

* Fixes an issue where the error struct is not initialized in `service.go` if `Error` is defined at the service level (#1526)
* Fixes segfault when error response is defined at the service level (#1527)

Fix code generation when error response defined in service-level

---

design/api.go
design/api_test.go

It should get only schemes which can be parsed and not empty.

Fix the condition to get schemes in APIExpr

---

goagen/gen_app/test_generator.go

Go version 1.10,  `go vet` command strictly detects not used variables in tests as follows:
```
$ go vet ./app/test/
app/test/bottle_testing.go:36:3: resp declared but not used
```
```go
func ShowBottleNotFound(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.BottleController, bottleID interface{}) http.ResponseWriter {
// Setup service
var (
logBuf bytes.Buffer
resp   interface{} // ← ★
respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
```
This patch fix it to generate it only when the `resp` is used.

Remove the unused valiable

---

design/attribute.go
dsl/result_type.go

This is so that checks that merely check for the presence of the metadata rather than whether the value is empty don't end up returning true.
Fixes #1554

Avoid setting empty view metadata on attributes when building views

---

codegen/service/convert.go

When building conversion method.
Fixes #1557

Properly ignore attributes with metadata indicating they should not be converted

---

design/attribute_test.go

#1423 
Now `validation` in the test cases is unneeded.

Remove unneeded test values

---

http/codegen/example_server.go

When running `goa example` on Windows, the import paths had `\` instead
of `/` since `filepath.Join` was being used instead of `path.Join`. For
example:
```golang
package main
import (
"context"
...
"github.com\douglaswth\blah"
)
...
```
This will not compile since `\` is used for escape sequences, etc.

Fix codegen imports on Windows

---

examples/calc/cmd/calcsvc/main.go
examples/cellar/cmd/cellarsvc/main.go
examples/tracing/cmd/calcsvc/main.go
http/codegen/example_server.go

- With Go 1.10 there is now a `go vet` error on the generated and
example server commands: `the cancel function returned by
context.WithTimeout should be called, not discarded, to avoid a context
leak`

Fix new go vet cancel function context leak issue

---

design/definitions.go
goagen/codegen/publicizer.go
goagen/codegen/publicizer_test.go
goagen/codegen/types_test.go

We fix an issue where non-required fields of kind Any were generated as
a pointer to *interface{}. This broke the Go compiler which failed with
the error "type *interface {} is pointer to interface, not interface".
To prevent this, we teach AttributeDefinition.IsPrimitivePointer that
AnyKind should never be converted to a pointer, since it already is an
interface.
The change also adds a test case.
```go
var NullAny = Type("NullAny", func() {
Attribute("value", Any)
})
```
```go
// nullAny user type.
type nullAny struct {
Value *interface{} `form:"value,omitempty" json:"value,omitempty" xml:"value,omitempty" bson:"value,omitempty"`
}
// Publicize creates NullAny from nullAny
func (ut *nullAny) Publicize() *NullAny {
var pub NullAny
if ut.Value != nil {
pub.Value = ut.Value
}
return &pub
} …
```

Prevent Any fields from pointing to *interface{}

---

design/definitions.go
goagen/codegen/publicizer.go
goagen/codegen/publicizer_test.go
goagen/codegen/types_test.go

This is a backport of the bugfix from `master` #1584 (86448e9) to the `v1` stable branch, as requested by @raphael.
-----
We fix an issue where non-required fields of kind "Any" were generated
as a pointer to *interface{}. This broke the Go compiler which failed
with the error "type *interface {} is pointer to interface, not
interface".
To prevent this, we teach AttributeDefinition.IsPrimitivePointer that
AnyKind should never be converted to a pointer, since it already is an
interface. The change also adds a test case.
This is a backport of #1584 to the "v1" stable branch.

Backport to v1: Prevent "Any" fields from pointing to *interface{}

---

http/middleware/logging/log.go

This is a minor fix to address a bug introduced in https://github.com/goadesign/goa/pull/1585. The old logger's log definition was `func (a *adapter) log(lvl string, keyvals ...interface{})`. so we initialized the vals to be of size n+1 and set the lvl at 0th index https://github.com/goadesign/goa/pull/1585/files#diff-c569e732b7a9e4f2486a8c37f7b06c98L42.

fix index out of bounds error

---

design/validation.go
design/validation_test.go

Hi. I noticed that goa design doesn't allow to use different wildcards at the same position for different methods. It's reasonable only if we check wildcard positions in URLs with the same HTTP method. But it's not reasonable to make this check if http methods are different.
My error was:
```
resource "decisions" action "list": route "/api/v1/decisions/:entity/:entityID/" conflicts with route "/api/v1/decisions/:decisionID" of decisions action delete. Make sure wildcards at the same positions have the same name. Conflicting wildcards are "entity" from route GET "/:entity/:entityID/" of resource "decisions" action "list" and "decisionID" from route DELETE "/:decisionID" of resource "decisions" action "delete".
```
So `DELETE "/:decisionID" ` was conflicting with `GET "/:entity/:entityID/"` …

validate different wildcards only if request method is the same

---

codegen/service/endpoint.go
codegen/service/endpoint_test.go
endpoint.go
examples/cellar/gen/http/sommelier/server/server.go
examples/cellar/gen/http/storage/server/server.go
examples/cellar/gen/sommelier/endpoints.go
examples/cellar/gen/storage/endpoints.go
examples/cellar/gen/swagger/endpoints.go
http/codegen/server.go
http/codegen/testdata/handler_init_functions.go
http/encoding.go

Add name of method and service to context created by transport .
This allows generic endpoint middlewares to take advantage of them.

Add Use method to generated Endpoints struct

---

design/apidsl/action.go
design/definitions.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_swagger/swagger.go

This is a backport of #1582 and #1596 to v1.

Add support for multipart form requests

---

goagen/codegen/types.go
goagen/codegen/types_test.go

A previous patch in [#1591][1] addressed an issue where optional fields
of kind "Any" would result in a pointer to interface. We fix an
additional occurence of this problem in private user types, which follow
slightly different logic than the public media types previously fixed
and add a test case for private defs.
[1]: https://github.com/goadesign/goa/pull/1591

Prevent pointer to '*interface{}' in user types

---

goagen/codegen/types.go
goagen/codegen/types_test.go

A previous patch in [#1591][1] addressed an issue where optional fields
of kind "Any" would result in a pointer to interface. We fix an
additional occurence of this problem in private user types, which follow
slightly different logic than the public media types previously fixed
and add a test case for private defs.
[1]: https://github.com/goadesign/goa/pull/1591
This is a backport of #1610 to the "v1" stable branch.

v1: Prevent pointer to '*interface{}' in user types

---

Makefile
service.go
service_test.go

Fix race condition that can occur when calling handlers returned from
Controller.MuxHandler where the Service's slice of middleware functions
is written to in a way that is not thread-safe.
The race will only occur when the capacity of the Service's middleware
slice is greater than its length and when the number of Controller
middlewares is more than 0. The functions returned by MuxHandler (that
are all from the same Controller object), if called in parallel, could
cause the race to occur.

Fix MuxHandler initialization race

---

design/definitions.go
design/random.go
design/types.go
design/validation.go
design/validation_test.go
goagen/codegen/types.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go

This pull request adds a new primitive type FIle.
It represents the `file` type of the Swagger specification.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
> An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.
It can be used with `MultipartForm` and It makes it possible to create a service that can be uploaded a file.

Add a primitive type File

---

examples/calc/gen/http/calc/server/server.go
examples/cellar/gen/http/sommelier/server/server.go
examples/cellar/gen/http/storage/server/server.go
http/codegen/server.go
http/codegen/testdata/handler_init_functions.go

Don't proceed to encoding the response if there was an error and
encoding the error was successful.

Fix the encode error

---

codegen/service/service.go
examples/cellar/design/api.go
examples/cellar/gen/storage/service.go
http/codegen/service_data.go

So that the code uses the proper comparison with the error name.

Fix how error responses are encoded

---

http/middleware/debug.go

Debug info was getting written to inner w (http.ResponseWriter) instead
of passed in writer.

Fix variable shadowing issue.

---

examples/cellar/gen/http/sommelier/client/encode_decode.go
examples/cellar/gen/http/storage/client/encode_decode.go
examples/error/gen/http/divider/client/encode_decode.go
http/client.go
http/codegen/client.go

Not necessarily a bug but every other error returned from the http client seems to be a goahttp.ErrXXX error so this helps keeps things consistent.

Add in validation error type for consistency

---

.gitignore
middleware/log_request.go
middleware/log_request_test.go

Minor change to `middleware/log_request.go` that allows the user to suppress sensitive headers from the log. Closes #1676.

added ability to suppress sensitive headers from log. closes #1676

---

.gitignore
middleware/log_request.go
middleware/log_request_test.go

Cherry picked v1 merge as per request in #1676
commit 2374869b71a94a85b0c24983bfb767fe2d6d3eec
Author: adam <ahanna@alumni.mines.edu>
Date:   Mon Apr 23 10:42:48 2018 -0700
moved suppressed headers map creation out of loop
commit 1ae9463a84186495c9b8b9a4c8bbf11e2a905d5a
Author: adam <ahanna@alumni.mines.edu>
Date:   Fri Apr 20 19:04:23 2018 -0700
removed swp files
commit 09cd41933fb5e955d23837b5694492970cd5084c
Author: adam <ahanna@alumni.mines.edu>
Date:   Fri Apr 20 18:59:32 2018 -0700
added ability to suppress sensitive headers from log. closes #1676
(cherry picked from commit 93f8814f17b49a9fc359ad4684cb39ee6fcf248c)

Cherry picked v1 merge as per request in #1676

---

codegen/validation.go
http/codegen/openapi/json_schema.go
http/codegen/openapi/openapi_v2_builder.go

Use type 'string' with format 'byte' instead of invalid type 'bytes'.
Fixes #1692

Fix handling of type Bytes in OpenAPI

---

http/codegen/openapi/openapi_v2_builder.go

Don't generate swagger docs if swagger:generate set at service level

---

goagen/gen_app/writers.go

Properly generate validation for URL parameter arrays

---

http/middleware/requestid.go
http/middleware/requestid_test.go

added options for RequestID middleware
same default behavior but with options to use incoming "X-Request-Id" header
added unit tests

use_x_request_id

---

codegen/service/endpoint.go
codegen/service/service.go
codegen/service/service_data.go
codegen/service/testdata/endpoint_code.go
codegen/service/testdata/service_code.go
codegen/service/testdata/views_code.go
codegen/service/views.go
design/method.go
examples/cellar/gen/http/storage/client/encode_decode.go
examples/cellar/gen/http/storage/client/types.go
examples/cellar/gen/storage/endpoints.go
examples/cellar/gen/storage/service.go
examples/cellar/gen/storage/views/view.go
http/codegen/client.go
http/codegen/service_data.go

* Fixes a case where required attributes may not be in a view.
* In HTTP client response decode, marshal response body if method uses a viewed result type so that the transformation code checks for nil before calling the helpers.
* Fix a bug when validating security scheme in method when payload is nil
* Remove suffix "Default" from validation and init functions. (Fixes #1734)

Various fixes

---

http/codegen/client.go
http/codegen/testdata/result_decode_functions.go

Fixes an issue in client response decode where it tries to validate the viewed result type even if the response body is empty.

Validate viewed result only if client body exists

---

middleware/log_request.go
middleware/log_request_test.go

Make request header logging order consistent

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go
middleware/sampler_test.go

* Added Action specific Consumes support for multipart
* Added unit test for multipart

Fix for v1 multipart/form-data Swagger semantic error (#1742)

---

goagen/gen_main/generator.go

when using goagen programmatically.
Fix #1728

Make sure default output dir is set

---

dsl/security.go

Adding the "In" and "Name" field to the JWTSecurity scheme expression so it generates a valid OpenAPI securityDefinitions section.
Before this change, a design with the following security scheme would generate an invalid OpenAPI securityDefinitions section.
Design:
```
var jwtSecurity = dsl.JWTSecurity("jwt", func() {
dsl.Description(`Secures endpoint by requiring a valid JWT token.`)
})
```
Output OpenAPI without these changes:
```
securityDefinitions:
jwt:
type: apiKey
description: |
Secures endpoint by requiring a valid JWT token.
**Security Scopes**:
```
When copy pasted to https://editor.swagger.io/, the OpenAPI causes:
```
Schema error at securityDefinitions['jwt']
should have required property 'flow'
missingProperty: flow
Schema error at securityDefinitions['jwt'].type
should be …
```

Generate Valid OpenAPI When JWTSecurity is Used

---

goagen/codegen/helpers.go
goagen/codegen/helpers_test.go

Hello,
I got the error when I build in the docker (golang image), where GOPATH is equal to "/go": 
```
• Failure [0.268 seconds]
Generate with a dummy API generated commands.go [It] generates "generated by" header
/go/src/github.com/goadesign/goa/goagen/gen_client/cli_generator_test.go:91
Expected
<string>: // Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "testapi": CLI Commands
//
// Command:
// $ goagen
// --out=$(GOPATH)/src/github.com$(GOPATH)adesign$(GOPATH)a$(GOPATH)agen/gen_client/test_
// --design=foo
// --version=v1.3.1
package cli
```
I made the fix that allows to replace the first match only.
Thanks

Fix client tests when GOPATH is /go

---

goagen/codegen/helpers.go
goagen/codegen/helpers_test.go

Hello,
It's a backport of #1766.
Thanks

Backport to v1: Fix client tests when GOPATH is /go (#1766)

---

design/apidsl/attribute.go
design/apidsl/attribute_test.go
design/definitions.go
design/definitions_test.go
goagen/gen_schema/json_schema.go
goagen/gen_schema/json_schema_test.go

* Add support for readonly attributes
* run go fmt
* use metadata to set readonly flag instead
#	design/apidsl/attribute.go

Backport to v1: Add support for readonly attributes (#1762)

---

codegen/service/auth_funcs.go
http/codegen/example_server.go

* Fixes #1770 
* auth.go is generated only if security schemes are defined in DSL
* Remove "DO NOT EDIT" comment from auth.go

Fix example generation

---

codegen/service/service_data.go
codegen/service/service_test.go
codegen/service/testdata/service_code.go
codegen/service/testdata/service_dsls.go
dsl/metadata.go

* Add "type:generate:force" in Metadata expression of a UserType to force its generation on the services even though the type is not used in the design. (#1574)

Force generate types from different package

---

design/apidsl/attribute.go
design/example.go
goagen/codegen/validation.go
validation.go
validation_test.go

Hello,
I added support of RFC3339 date format. This format exists in [Swagger 2.0 Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types).
Thanks

Add RFC3339 date format

---

codegen/service/convert.go
codegen/service/convert_test.go
codegen/service/testdata/alias-external/alias.go
codegen/service/testdata/convert_dsls.go
codegen/service/testdata/convert_functions.go
codegen/service/testdata/create_dsls.go
codegen/service/testdata/create_functions.go
codegen/service/testdata/external/external.go
codegen/testing.go

convert.go external imports where being omitted if the package name didn't match the file name.

added import aliases to external packages in convert.go

---

design/mapped_attribute.go
design/method.go
design/method_test.go
eval/eval.go
eval/expression.go
http/codegen/openapi/json_schema.go
http/codegen/openapi/openapi_v2_builder.go
http/codegen/openapi_test.go
http/codegen/service_data.go
http/design/body_types.go
http/design/endpoint.go
http/design/response.go
http/design/response_test.go
http/design/root.go
http/design/service.go
http/dsl/http.go

Added a new "Prepare" phase during code generation.
The endpoint expression flattens params and headers during "Prepare".
This alleviates the need for separating between values set at design
and values used to validate and generate the code.
This also helps in making the use of the "a:b" notation handling more
consistent as the code now always uses mapped attributes.

Cleanup processing of parameters and headers in requests and responses.

---

design/definitions.go
design/definitions_test.go

Inherit query string parameters defined in API

---

http/design/endpoint.go
http/dsl/http.go

Fail validation if params, headers, or body present but Payload is not defined

---

design/result_type.go

When a seen result type is projected again using a different view, the code [inadvertently modifies the type of the original seen result type](https://github.com/goadesign/goa/blob/3b65d562232cb3c28c971119e27ac3b1075dc191/design/result_type.go#L302) instead of modifying a copy.

Fix Project for seen user types

---

codegen/service/convert.go
codegen/service/convert_test.go
codegen/service/testdata/convert_functions.go
codegen/service/testdata/create_functions.go
codegen/service/testdata/types.go
codegen/transform.go
design/root.go
eval/eval.go
examples/chatter/gen/http/openapi.yaml
http/design/endpoint.go

Fix multiple issues with validations and CreateFrom/ConvertTo:
* Validate that fields used on external types that are of type struct use a pointer.
* Fix potential name clash in conversion helper function names in case external and design types have identical names.
* Properly validate that HTTP path and query parameters have corresponding payload attributes.
Fix #1853

Fix create and convert

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

bugfix for #1862
type errors occur when set MultipartForm flag

bugfix type error in multipart-form payload

---

README.md

it seems to not be changed when v1.4.0 released.
and, this is just a little opinion.
I think v1 "stable" branch will update to 1.4.1 with when some bugfix merged.
I did not think the branch is managing the stable version ( sorry, I did not realize when I send previous PR ), so I merged the fix. But the stable branch, I think, should merge bunch of fixes when the next release comes. not every time PR comes.
someone may think the "v1 stable" branch is same as last released v1.x version.
so its current state should released with 1.4.1 as soon as possible or revert to v1.4.0 taged version and make other working branch for next update.

fix current version

---

design/server_test.go

This should close #1702 and close #1707 (which is for ServerExpr but it seems that the Attribute() method is now implemented by HostExpr).

add simple tests for ServerExpr and HostExpr

---

design/api_test.go

In #1864, `api_test.go` was removed but I think some tests can be kept? This PR is to bring back some of the test cases. Please feel free to ignore/close this PR if the removal of àpi_test.go` was intentional.

Bring back tests for api

---

codegen/service/convert_test.go
codegen/service/testdata/convert_dsls.go
codegen/service/testdata/convert_functions.go
codegen/service/testdata/create_dsls.go
codegen/service/testdata/create_functions.go
codegen/service/testdata/types.go
codegen/transform.go
codegen/transform_test.go

Fix the code generation for ConvertTo/CreateFrom when the source/target types contains an attribute with an external name

---

http/dsl/http.go

Allow HTTP DSL to be defined at API level to define common errors across services.

Support HTTP DSL in API for defining common errors across services

---

http/codegen/server.go
http/codegen/server_encode_test.go
http/codegen/service_data.go
http/codegen/testdata/result_dsls.go
http/codegen/testdata/result_encode_functions.go

Fixes a case where server response encode generation fails when there are multiple empty success responses in the endpoint.

Fix encoding multiple empty responses

---

dsl/validation.go

Allow targeting user types as well as objects.
Fix #1844

Fix 'Required' validation

---

codegen/service/convert.go

Protect 'ConvertTo' against multiple identical marshaler functions.
Fix #1860

Fix convert to duplicate marshal

---

http/codegen/service_data.go

When generating CLI tool source code.
Fix #1868

Properly handle non-object payload types

---

design/random.go
design/types.go
goagen/codegen/helpers.go
goagen/codegen/helpers_test.go
goagen/codegen/workspace.go
goagen/gen_app/encoding_test.go
goagen/gen_app/generator_test.go
goagen/gen_app/test_generator_test.go
goagen/gen_app/writers_test.go
goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_controller/generator.go
goagen/gen_controller/generator_test.go
goagen/gen_js/generator_test.go
goagen/gen_main/generator_test.go
goagen/gen_schema/generator_test.go
goagen/gen_schema/json_schema_test.go
goagen/gen_swagger/generator.go
goagen/gen_swagger/generator_test.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go
goagen/meta/generator.go
goagen/meta/generator_test.go
logging/kit/adapter_test.go
logging/log15/adapter_test.go
logging/logrus/adapter_test.go
metrics.go
metrics_test.go
uuid/uuid.go

Go v1.8+ set a default GOPATH if the GOPATH env variable is not set. This patch makes it possible to use `goagen` with a default GOPATH.
I found this issue during trying to improve goa to support Go modules (for #1914). I'm plannning to open another pull request for that.

Use build.Default.GOPATH instead of env GOPATH

---

goagen/codegen/workspace.go
goagen/codegen/workspace_test.go

Support Go 1.11 Modules by goagen

---

goagen/gen_swagger/generator.go
goagen/gen_swagger/generator_export_test.go
goagen/gen_swagger/generator_test.go

Converting JSON to YAML, we need yaml.Unmarshal to keep the right number type.
via https://github.com/ghodss/yaml/blob/f5bccc04aa10faf16af8a8c9664a452bf7d80101/yaml.go#L65-L81
An example is here.
```
apidsl.Attribute("id", design.Integer, "Unique bottle ID", func() {
apidsl.Example(1234567)
})
```
Using json.Unmarshal, goagen swagger generates this swagger.yaml.
```json
id:
description: Unique bottle ID
example: 1.234567e+06
format: int64
type: integer
```
After using yaml.Unmarshal, goagen swagger generates this swagger.yaml.
```json
id:
description: Unique bottle ID
example: 1234567
format: int64
type: integer
```

Use yaml.Unmarshal for swagger.yaml

---

Makefile

`make depend` didn't work on Mac.
So I added darwin case to Install protoc block.

add protoc install setting for MacOS

---

goagen/codegen/helpers.go
goagen/codegen/helpers_test.go
goagen/codegen/workspace.go
goagen/meta/generator.go
goagen/meta/generator_test.go

* Use build.Default.GOPATH instead of env GOPATH
* Specify package name for some packages

Use build.Default.GOPATH instead of env GOPATH (#1930)

---

README.md

Modification to the instructions for implementing swagger.
The file to add the swagger import is in the `cmd/calcsvc/calcsvc.go` not `cmd/calcsvc/main.go`.

Incorrect file to put import for implementing swagger

---

middleware/xray/middleware.go
middleware/xray/middleware_test.go
middleware/xray/segment.go
middleware/xray/segment_test.go
middleware/xray/transport.go
middleware/xray/transport_test.go
middleware/xray/wrap_doer.go
middleware/xray/wrap_doer_test.go

Modernize the the goa X-Ray segments to support writing "In Progress" segments to the xray-daemon.
This way, in the X-Ray UI we can see a live view of what is happening in the system, with "Pending" segments and their hierarchy visible.
The current behavior is that X-Ray is only notified about a segment when it is fully completed, which could take several minutes. Meanwhile, the trace in the UI is confusing, missing the key top-level hierarchy while subsystems have already started reporting their completed segments.
This PR makes the following changes:
- Add the `SubmitInProgress` method to `xray.Segment`. Whoever creates the segment can call this method shortly afterwards to ensure the X-Ray UI will immediately show the segment, as "Pending".
- `xray` middleware, `xray.WrapDoer`, and …

IND-1925 X-Ray tracing record in-progress requests

---

examples/basic/gen/grpc/cli/calc/cli.go
examples/basic/gen/http/cli/calc/cli.go
examples/cellar/gen/grpc/cli/cellar/cli.go
examples/cellar/gen/http/cli/cellar/cli.go
examples/error/gen/grpc/cli/divider/cli.go
examples/error/gen/http/cli/divider/cli.go
examples/multipart/gen/http/cli/resume/cli.go
examples/security/gen/grpc/cli/multi_auth/cli.go
examples/security/gen/http/cli/multi_auth/cli.go
examples/streaming/gen/grpc/cli/chatter/cli.go
examples/streaming/gen/http/cli/chatter/cli.go
grpc/codegen/client_cli.go
http/codegen/client_cli.go
http/codegen/testdata/parse_endpoint_functions.go

This fixes the generated cli code to properly handle non-boolean flags.  Currently in v2 specifying a url causes the request to fail:
```
$  go run examples/basic/cmd/calc-cli/* -url http://localhost:8080 calc add -a 1 -b 2
unknown service "http://localhost:8080"
run '/var/folders/yc/0j7srrz91g35b3l3w6g06q380000gn/T/go-build461741860/command-line-arguments/_obj/exe/grpc --help' for detailed usage.
exit status 1
```

Fix cli flag handling

---

grpc/codegen/proto_test.go
grpc/codegen/service_data.go
grpc/codegen/testdata/dsls.go
grpc/codegen/testdata/proto_code.go

`protoBufify` is applied inconsistently when the method is a reserved name. Resulting in different signatures to the protobuf message types and method signature.
```go
package design
import . "goa.design/goa/dsl"
var _ = Service("My Great Cat Service", func() {
Method("rpc", func() {
Result(Empty)
GRPC(func() {
Response(CodeOK)
})
})
})
```
```shell
➜ goa gen github.com/allofthesepeople/goatest/design
exit status 1
failed to run protoc: exit status 1: my_great_cat_service.proto:17:18: "Rpc_Request" is not defined.
my_great_cat_service.proto:17:40: "Rpc_Response" is not defined.
```
resulting in a protofile where the service definition signatures do not match the Message types:
```proto
…
service MyGreatCatService {
// RPC implements rpc.
rpc RPC (Rpc_Request) returns (Rpc_Response);
} …
```

Messages called from rpc match message names when reserved name

---

dsl/security.go
http/codegen/openapi.go
http/codegen/testdata/openapi_v2_dsls.go

Add back OpenAPI test that got removed when the logic to skip OpenAPI generation for designs that
do not include HTTP services was introduced.

Add OpenAPI test

---

codegen/cli/cli.go
dsl/headers.go
dsl/http.go
dsl/validation.go
expr/http_endpoint.go
expr/http_response.go
grpc/codegen/client_cli.go
http/codegen/client.go
http/codegen/client_cli.go
http/codegen/client_cli_test.go
http/codegen/client_decode_test.go
http/codegen/client_types.go
http/codegen/server.go
http/codegen/server_decode_test.go
http/codegen/server_types.go
http/codegen/service_data.go
http/codegen/testdata/parse_endpoint_functions.go
http/codegen/testdata/payload_decode_functions.go
http/codegen/testdata/payload_dsls.go
http/codegen/testdata/result_decode_functions.go
http/codegen/testdata/result_dsls.go
http/codegen/testdata/result_encode_functions.go

* Fixes bug where adding `Params` or `Headers` DSL inside HTTP endpoint had no effect
* All headers are encoded/decoded in the [canonical header key format](https://godoc.org/net/http#CanonicalHeaderKey).
* Fixed DSL documentation for `Headers` and `Params` to take only function type as argument. It doesn't make sense to use a UserType here to define params and headers since we map the params and headers to the service payload and result types.
* Path parameters are now always required flags in the HTTP CLI

Add support for Params and Headers DSL

---

http/codegen/client.go
http/codegen/service_data.go
http/codegen/testdata/streaming_code.go

added code-generated go-routine to support cancellation of context associated with websocket streaming server request on client side.
check for nil websocket connection in server Close() to avoid panic when application does not know exactly when close needs to be called. also we must not upgrade to websocket when we are attempting to close stream because that prevents responding with http status code when request fails.

websocket_client_cancel

---

error.go

I fixed an error in XML marshalling of ErrorResponse which is reported with #1114.

Fix error `xml: unsupported type: map[string]interface {}`

---

codegen/generator/example.go
codegen/generator/service.go
codegen/generator/transport.go
codegen/header.go
codegen/import.go
codegen/scope.go
codegen/service/service.go
codegen/types_test.go
dsl/meta.go

I also tried to solve a bug in Goa 1 which didn't place the user defined import inside all of the files, just user_types, which led to issues when using this meta tag with Payloads.
Since ImportSpec takes in an additional Name parameter I figured adding qualified imports would be useful as well.
I also noticed the AddImports function wasn't being used anywhere within goa, and made the signature more useful.

https://github.com/goadesign/goa/issues/2013 struct:field:type implementation

---

codegen/generator/example.go
codegen/generator/service.go
codegen/generator/transport.go
codegen/header.go
codegen/import.go
codegen/scope.go
codegen/service/service.go
codegen/types_test.go
dsl/meta.go

* Added support for struct:field:type, added new functions for adding imports to codegen.File and added a new parameter to struct:field:type that allows qualified imports. Meta imports are available for method payloads to use as well
* added comments, maintained backward compat with AddImport, unexported GetMetaType
* appeased linter, added tests to to types_test.go, clarified pointer caveat with struct:field:type
* aligned comments
* fix infinite recursion

struct:field:type implementation (#2053)

---

codegen/go_transform.go
codegen/service/service_data.go
codegen/service/testdata/service_code.go

when assigning to transform target variable.
Remove invalid check as we still need to dereference
even when assigning raw struct e.g.:
```go
if res.Parent != nil {
vres.Parent = &struct {
Child *string
}{
Child: res.Parent.Child,
}
}
```

Properly dereference raw struct
