codegen/gen_app/writers.go
codegen/types.go

in type unmarshaler code (e.g. new payload methods).

Properly generate required attributes validation

---

codegen/gen_gen/command.go
codegen/gen_gen/command_test.go
codegen/gen_gen/docs.go
codegen/gen_gen/gen_gen_suite_test.go
goagen/main.go

See "gengen" package documentation.

Add third party generator support

---

application.go
application_test.go
codegen/gen_app/generator_test.go
codegen/gen_app/writers.go
context.go
context_test.go
examples/cellar/account.go
examples/cellar/app/contexts.go
examples/cellar/bottle.go
goa_suite_test.go
middleware.go
middleware_test.go

Fix all issues uncovered by tests.

Improve test coverage

---

goagen.md
goagen/bootstrap.go
goagen/gen_app/command.go
goagen/gen_app/generator.go
goagen/gen_main/command.go
goagen/main.go

And make sure implementation matches described behavior.

Improve goagen docs

---

error.go
error_test.go
validation_test.go

Handle identified corner cases properly

Add tests for errors and validations

---

design/definitions.go
design/dsl/action.go
design/dsl/attribute.go
design/types.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/codegen/validation.go
goagen/gen_app/writers.go

Make sure attributes are properly copied when inherited
so that changing the child doesn't change the parent.

Fix bugs in generation of validation code

---

design/definitions.go
design/types.go
goagen/codegen/types.go
goagen/gen_app/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/json_schema.go

Get rid of singularization of resource names.

Fix generation of primitive user type unmarshalers

---

middleware.go
middleware_test.go

@raphael added goa.RequireHeader() middleware with tests

required_header_middleware

---

goagen/codegen/types.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/writers.go

Make sure pattern validation always apply

---

examples/cellar_test.go

* test cannot pass on my machine because `pwd` is not in `$PATH`
* after test, temp dir should be deleted

Explicitly invoke cellar and cleanup after test

---

goagen/main.go

Fix goagen --help not display subcommands

---

goagen/gen_gen/doc.go

add goagen to the path of the example generator code

Correct path in example code

---

examples/cellar/js/client.js
goagen/gen_js/generator.go

Fix missing "utils" reference in generated JavaScript.

---

design/definitions.go
design/dsl/action.go
design/dsl/media_type.go
design/dsl/media_type_test.go
design/dsl/resource.go
design/dsl/resource_test.go
goagen/codegen/types_test.go
goagen/gen_app/generator.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Allow id in CollectionOf

---

examples/cellar_test.go
goagen/bootstrap.go
goagen/gen_app/generator.go
goagen/gen_client/generator.go
goagen/gen_js/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/generator.go
goagen/gen_swagger/generator.go
goagen/main.go
goagen/utils/signal.go

I did not make changes to cleanup logic so directory `app` `swagger` `client` are not deleted as well.
But it's reasonable as we may mistakenly delete user's code in the same directory.

Handle signal gracefully

---

design/dsl/media_type.go
design/dsl/media_type_test.go

Add missing nil check in Media.

---

goagen/gen_gen/doc.go

Refer to metadata in plugin docs.

---

examples/cellar_test.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_js/generator.go
goagen/gen_js/generator_test.go
goagen/gen_schema/generator.go
goagen/gen_schema/generator_test.go
goagen/gen_swagger/generator.go

Remove generated directories, #94

---

Makefile

Fix make failed on fresh environment

---

Makefile
goagen/gen_swagger/generator.go

Cleanup Makefile to remove extraneous dependency.

Add missing import to generated swagger controller.

---

goagen/gen_app/generator.go
goagen/gen_schema/generator.go
goagen/main.go

And add check for `goimports` in `goagen`.

Fix generated imports

---

goagen/codegen/types.go
goagen/codegen/types_test.go

Make sure to use the right key native type.

Fix issue with hash marshalling.

---

Makefile
design/definitions.go
design/validation.go
goagen/codegen/generator.go
goagen/gen_client/generator.go
goagen/gen_js/generator.go
goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger.go
goagen/meta/generator.go

Code cleanup

---

context.go
service.go

So that the service middleware chain is used when handling serve file requests.

Create a proper controller to serve files.

---

appveyor.yml
examples/cellar_test.go
goagen/codegen/helpers.go
goagen/codegen/types_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
goagen/gen_gen/command_test.go
goagen/gen_js/generator_test.go
goagen/gen_main/generator.go
goagen/gen_main/generator_test.go
goagen/gen_schema/generator_test.go
goagen/meta/generator.go
goagen/meta/generator_test.go
goagen/utils/signal.go
goagen/utils/signal_lin.go
goagen/utils/signal_win.go

Need to merge to master so `go get ...goagen` picks up the changes for
appveyor Windows build.

First pass at making goa Windows compatible.

---

design/definitions.go
examples/cellar_test.go
goagen/codegen/types_test.go
goagen/gen_client/generator.go
goagen/gen_gen/command.go
goagen/gen_main/generator.go
goagen/meta/generator.go
goagen/meta/generator_test.go

All tests pass now.  One oddity: I had to increase the timeout on the
examples test to 200ms on my windows box.
I've noticed that startup times on Windows are often slower than on Linux.  What's funny is that I can run a Linux VirtualBox VM on this same Windows machine, and the 100ms test passes every time.

Another pass at windows support

---

goagen/gen_app/generator.go

use the VersionPackage() function to get the package name for templates.

correct version package name

---

service.go

e.g. "application/json;charset=UTF-8"

Decode payload when content type as parameters

---

middleware.go
middleware_test.go

added LogResponse() to middleware

log_response

---

goagen/gen_client/generator.go

Removes stray "nil" from client return

fix client compilation error

---

goagen/codegen/types.go
goagen/gen_app/writers.go

Add "Validate" method to payload types.

Fix validation of types after unmarshaling

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

Fix issue with minimum value validation code.

---

goagen/gen_app/writers.go

As they now get loaded and dumped to and from JSON directly

Generate JSON tags on payloads and media types

---

service.go

Also change GetVersion to Version

Change Version interface to ServiceVersion

---

service.go

Make root mux accessible from Service interface.
Creating the service embedded version must not create a version mux to avoid calling into the select version algorithm when no version is specified.

Fixup mux initialization

---

goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go

Fix up issues with code generation

---

design/dsl/type.go

I was looking for it.. and it's quite similar in concept to ArrayOf.
Maybe adding other distinguishing features of both in the doc would help.

Added note to refer to CollectionOf in the ArrayOf doc.

---

design/dsl/attribute.go
design/dsl/attribute_test.go

To allow circular dependencies.

Make it possible to define attribute type by name.

---

getting-started.html
index.html
runtime.html

also includes a few tiny html fixes my linter recommended.

fix dsl package name

---

goagen/codegen/types.go
goagen/codegen/types_test.go

Fix GoTypeTransform generated field names

---

goagen/codegen/types.go

Properly use target package when creating new object type

---

error.go

#252 Validation error should say "...must match..." instead of "...must be match..."

---

TODO.md
design/apidsl/media_type_test.go
design/types.go
design/types_test.go
goagen/meta/generator.go

Otherwise generated code makes references to the `app` package
when it shouldn't.
Also fix issue where errors run during the DSL load phase would get
skipped.

Fix Project so it properly carries Versions

---

design/apidsl/media_type_test.go
design/example.go
design/types.go

Address issues: #259 and #260
- fix the div zero panic while generating examples
- handle `AnyKind` example
- add couple more safety checks while generating examples

Address Issue #259 and #260

---

goagen/gen_app/generator.go
goagen/gen_app/generator_test.go

Generate proper encoder factory function name

---

design/api.go
design/apidsl/attribute.go
design/dup_test.go
design/types_test.go
goagen/gen_app/writers.go
goagen/gen_client/doc.go
goagen/gen_client/generator_test.go
goagen/gen_schema/json_schema.go
mux.go
service.go

Changed files in accordance to the issues filed at: https://github.com/goadesign/goa/issues/280 and https://github.com/goadesign/goa/issues/281. Just some minor spelling changes and formatted code :)

corrected spelling, formatted code with gofmt -w -s <filename>

---

goagen/gen_app/generator.go

goagen: add time import to app contexts

---

design/apidsl/attribute.go
design/apidsl/attribute_test.go
design/definitions.go
design/definitions_test.go
design/dup.go
design/example.go
design/types.go
design/validation_test.go
dslengine/definitions.go
dslengine/validation_test.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers_test.go
goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger.go

To simplify and fix bugs with duplicated validations.

Rework validation definitions

---

goagen/codegen/types.go
goagen/codegen/types_test.go

This commit fixes Goify to recognize the same initialisms that golint does.  Also adds several tests.

Fix up Goify to understand initialisms

---

context.go
doc.go
encoding.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_js/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/generator.go
goagen/gen_swagger/generator.go
graceful.go
middleware_test.go
mux.go
service.go
service_test.go

To prepare for the versioning mux codegen.

Cleanup Mux and Service abstraction.

---

goagen/codegen/types.go
goagen/codegen/types_test.go

fixes the fixes for 295, adding more tests for positive and negative cases

Fix Goify for edge (non goa) cases

---

goagen/codegen/types.go
goagen/codegen/types_test.go

codegen: honor initialisms in lowercase Goify

---

mux.go
mux_test.go

They are already validated by goagen.

Remove runtime validation of version params

---

design/apidsl/metadata.go
design/apidsl/metadata_test.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

Follow up on https://github.com/goadesign/goa/issues/305

Implemented metadata with extensible model, and swagger generation.

---

design/definitions.go

Response DSL function as second argument.

Use the MediaType identifier when a MT is supplied to the

---

context.go
error.go
error_test.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_js/generator.go
logging.go
service.go
service_test.go

So that error responses are serialized using the default
encoder rather than hardcoded to JSON.

Update error handling

---

error.go
error_test.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Rename BuildError into StackErrors

---

goagen/gen_app/generator.go
goagen/gen_app/writers.go
security.go

Created off of @abourget's PR minus `DetailedError` addition.

Simplification of the config protocol for security handlers.

---

goagen/gen_main/generator.go
graceful.go

Also added Timeout to ListenAndServe for graceful services.
(there's no `SetTimeout` anymore).

Generate graceful in new services (gen_main)

---

service.go
service_test.go

Protect against request bodies with unreasonable length

---

error.go
goagen/codegen/types_test.go
service.go
service_test.go

Change "request too large" response to use status 413.

---

goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Properly handle params coming in as slices of multiple elements.

---

goagen/codegen/command.go

This is a changing for beginners of `goagen` like me.

Change the usage for design flag of goagen

---

context.go
goagen/gen_main/generator.go
middleware/log_request.go
middleware/log_request_test.go
service.go

* Add "from" key with client IP
* Only log controller and action in "started" log
* Use controller name instead of resource name

Improve request logger middleware.

---

context.go
goagen/gen_main/generator.go
middleware/log_request.go
middleware/log_request_test.go
service.go

Fix not found context

---

context.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_main/generator.go
middleware/log_request.go
middleware/log_request_test.go
service.go

Fix service init

---

design/types.go

Fix lack of Any in Primitive.IsCompatible()

---

error.go
error_test.go

Properly initialize error MetaValues.

---

context.go
goagen/gen_app/writers.go
goagen/gen_client/generator.go
logging.go
logging/doc.go
logging/kit/logger.go
logging/log15/logger.go
logging/logrus/logger.go
middleware/log_request.go
middleware/middleware_test.go
service.go
service_test.go

To follow "net/context" conventions.
goa-cellar follows..

BREAKING: UseLogger -> WithLogger, ActionContext -> WithAction, LogWith -> WithLog

---

design/types.go

I think perhaps this is better.

Fix: Panic on unknown type in IsCompatible

---

design/apidsl/attribute.go

Add example to Example()

---

goagen/gen_js/generator.go
goagen/gen_js/generator_test.go

Correctly handle querystring params in gen_js.

---

goagen/bootstrap.go
goagen/gen_test/command.go
goagen/gen_test/command_test.go
goagen/gen_test/doc.go
goagen/gen_test/gen_client_suite_test.go
goagen/gen_test/generator.go
goagen/gen_test/generator_test.go
goagen/main.go
goatest/testing.go

The test generator generates test helpers for the API controllers.
A test helper is generated for all combination of
Resource/Action/Route/Response/View.
The test helpers can be found in ./test/$resource.go

Add gen_test generator

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

cors: fix multiple instances of `Origin()`'s gen_app generator.

---

goagen/gen_client/generator.go

Instead of referring to the data structures generated
by gen_app.

Generate payload structs inline.

---

goagen/gen_client/generator.go

So that all user types are generated - not just payload types that may
depend on others.

Fix client code generation

---

goagen/codegen/helpers.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go

And use it everywhere it's needed.

Improve snake casing algorithm.

---

goagen/gen_app/test_generator.go

Fix a param of RecursiveChecker() for the payload

---

goagen/gen_client/generator.go

For path functions that correspond to different routes on the same
action and resource. This is in `gen_client`.

Append unique index at the end of the generated Path functions.

---

goagen/gen_app/test_generator.go

Ordering of functions in `app/test` is not guaranteed to be the same from one iteration to the next.
We should use prepared keys to iterate over maps.

Fix ordering of functions generated by goagen

---

goagen/gen_main/generator.go

This can happen with the use of `CollectionOf`.

Make gen_main handle media types with no default view.

---

design/definitions.go

Inherit Example for referenced attributes

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Set route path parameters

---

design/definitions.go
design/definitions_test.go

fix nil-pointer exception in IterateHeaders()

---

service.go

Parameters probably are the opposite.

Fix serve file

---

error.go
goagen/gen_app/writers.go
middleware/security/basicauth/basicauth.go
middleware/security/jwt/jwt.go
middleware/security/jwt/jwt_test.go
security.go

By using standard goa middleware instead of custom "config" functions.

Simplify security setup.

---

design/definitions.go

Let actions explicitly list responses, that's what everybody expects...

Do not merge responses defined in API in all actions.

---

design/definitions.go
goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go

Fix ordering of arguments in calls to client methods

---

design/definitions.go
error.go
goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go
service.go

Add client "download" command

---

goagen/codegen/types.go
goagen/codegen/types_test.go

Fixed Goify issues with leading, trailing and consecutive invalid identifiers

Fix Goify consecutive invalid identifiers

---

encoding/form/encoding.go

Add explicit support for x-www-form-urlencoded encoding

---

error.go
goagen/codegen/publicizer_test.go
goagen/codegen/types.go
goagen/codegen/types_test.go

To properly support form encoding.
How tags are added is something that will have to be refactored, for now
the list is hardcoded.

Add form tags to generated data structures.

---

goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go

This applies when creating requests. The CLI also has a new --content flag.

Add ability to specify content type in client.

---

client/client.go
design/random.go
design/types.go
goagen/gen_app/generator.go
goagen/gen_client/generator.go
metrics.go
metrics_js.go
uuid/common.go
uuid/uuid.go
uuid/uuid_js.go
validation.go

Those three commits, allow building with gopherjs against the client generated go code.

Add support for the generated client go code for Gopherjs 

---

logging/log15/adapter.go
logging/log15/adapter_test.go
middleware/security/jwt/jwt.go

See https://github.com/inconshreveable/log15/issues/80

Switch to github.com for log15 Go import path

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Allow empty responses in test helpers
Also return response writer so caller may inspect headers

Tweak test generation

---

goagen/gen_app/test_generator.go

Maybe it is a regression bug of #570.

Use appropriate types for each endpoints in app tests

---

design/apidsl/resource.go
design/definitions.go
goagen/gen_app/test_generator.go
middleware/security/jwt/jwt.go

Also tweak test generator to return error response when testing BadRequest
action responses.

Correctly merge resource responses into action's.

---

goagen/gen_app/writers.go

When using a media type as response type using the syntax:
```
Reponse(OK, MediaType)
```

Properly generate view specific response methods.

---

error.go
error_test.go

Please review tests, didn't spend too much time to figure out the proper way to use Ginkgo

Fix error merge when target metadata is nil

---

error.go
error_test.go

Follow up to PR #590

---

goagen/gen_main/generator.go

PR for discussion in #592 
Example: https://github.com/goadesign/examples/pull/6
change TBD to <controller>_<func> [start/end]_implement tar pairs
This enables an external tool to manage code regeneration without disruption existing modifications.

Change TBD tags to start/end block pairs

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Correctly handle required query string params

---

goagen/codegen/types.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go

to define Go struct field name.

Fix validation code of structs using metadata

---

goagen/main.go

Issue #555 fix help for -o flag

---

design/definitions.go

So that JSON encoder doesn't loop infinitely for example.

Prevent generation of cycles in generated examples.

---

design/definitions.go

Since null is not a valid JSON schema type.

Avoid generating null values in Swagger examples.

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Request headers are now properly set in the request context.

Fix handling of request headers.

---

error.go
error_test.go

Per discussion in slack #goa, exporting errorResponse.

Export errorResponse struct

---

client/client.go

* Introduce utility funcs for getting/setting request ID in Context
* Set X-Request-Id header on the request from the context (at some point this should be done in a client middleware)

Request ID is set in ctx and in req header

---

design/types.go
goagen/codegen/types.go
goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_client/generator.go

Properly generate decode function for error responses.

Handle error media type more explicitly.

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

Fix the handling of the zero value validations

---

design/apidsl/attribute.go
design/example.go
goagen/codegen/validation.go
validation.go
validation_test.go

PR for #557
Add format IP validation (either IPv4 or IPv6)

Add format IP validation (either IPv4 or IPv6)

---

design/apidsl/media_type_test.go
design/definitions.go
design/example.go
design/types.go
goagen/gen_js/generator.go

Properly handle recursive cycle and unify generation of random values
with finalization of attributes.

Improve example generation.

---

goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go

Generate direct access to cmd.FieldName when resolving path params

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Even if it's invalid so that its content can be logged properly

Always initialize request payload

---

goagen/gen_app/writers_test.go

Add test for ContentType code generation

---

error.go
error_test.go

Properly handle float range errors

---

goagen/gen_main/generator.go

Handle special case where OK resposne returns ErrorMedia

Correctly handle OK error response in genmain

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Fix generated for Href helper for param-less actions

---

goagen/codegen/types.go

To avoid clashes with net/url package

Add 'url' to list of reserved names

---

goagen/gen_swagger/swagger.go

Properly handle / BasePath in Swagger generation

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Created a test for the missing header.
Created the header by adding a title to WriteHeader

address issue https://github.com/goadesign/goa/issues/738 

---

design/apidsl/action.go
design/apidsl/action_test.go
design/apidsl/metadata.go
design/apidsl/metadata_test.go
design/definitions.go
design/security.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

This is a backport of #779 to [v1](https://github.com/goadesign/goa/releases/tag/v1.0.0).
Please merge after #782.

Support swagger extensions

---

client/signers.go

when signing via query strings.

Fix API key signer

---

design/apidsl/metadata.go
goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

Try to use swagger extensions as JSON by default

---

middleware/error_handler.go
middleware/error_handler_test.go

@raphael as requested. I cherry picked the commit from master.

Add ability to log backtraces to ErrorHandler middleware (#792)

---

.travis.yml
goagen/gen_app/generator.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go
goagen/gen_swagger/generator.go

Fix bootstrap force flag

---

.travis.yml
goagen/gen_app/generator.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go
goagen/gen_swagger/generator.go

V1.fix bootstrap force flag

---

.travis.yml
design/example.go

Make sure array example length is at least 1

---

design/apidsl/action.go

Protect against malformed DSL

---

design/validation.go

Validate that action params are primitives or array of primitives

---

design/apidsl/attribute.go
design/types.go
design/types_test.go

When using incorrect syntax that leaves the definition attribute type nil
Fix #822

Fix Type DSL panic

---

service.go

* Add ListenAndServeUnix
* Revert "Add ListenAndServeUnix"
This reverts commit 33f8e6ec22690d7d98ac5a7bda434724e281b3c2.
* Add Serve function for any listner can start
* Fix comment
ref: #837

Add Serve function for any net.Listener starts serve

---

design/apidsl/type.go
design/apidsl/type_test.go

To enable recursive type definitions

Allow using type name with ArrayOf

---

goagen/codegen/finalizer.go
goagen/codegen/finalizer_test.go
goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/codegen/workspace.go
goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_app/writers.go

When generating code for validating and finalizing user types.

Properly handle recursive data types

---

design/dsl/description.go
design/dsl/endpoint.go
design/dsl/endpoint_test.go
design/dsl/metadata_test.go
design/dsl/url.go

@raphael Started a test for the Endpoint dsl. I couldn't find the ```Response``` func so I am assuming it is not yet there. Let me know if I am on the right track with this one.

Issue 845 dsl test endpoint

---

goagen/gen_app/test_generator.go

Add uuid to test helper imports. Fixes #870

---

goagen/meta/generator.go

Fix command line creation

---

design/dsl/endpoint_test.go

@raphael Made a pass at the improvements discussed around test composition. I removed some test cases for brevity, but will add them back afterwards. 
Essentially each test case has its own DSL definition and assert func

make a pass at test improvements

---

goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger.go

When the response sets a specific view.

Fix view used to render media types in Swagger

---

design/apidsl/attribute.go

Initialize attribute type even if name is invalid

---

design/types.go

Fix incorrect media type example

---

goagen/gen_client/generator.go

That is only if API supports multiple inbound content types.
Fix #881

Only generate "contentType" argument for clent methods when necessary

---

goagen/gen_app/test_generator.go

So that only tests for responses that return ErrorMedia do not fail and others compile.
Fix #883

Fix payload validation handling in tests

---

goagen/gen_schema/json_schema.go
goagen/gen_schema/json_schema_test.go

Swagger definitions reference not working from updaged latest goa .
maybe ref #878 
via https://github.com/goadesign/goa/pull/897#issuecomment-261984051

fix unlinked reference (v1)

---

goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Add arguments for setting header values in test functions

---

goagen/gen_client/generator.go

Properly configure websocket request with headers

---

goagen/gen_client/generator.go

header websocket client support

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go
goagen/gen_app/writers.go

Avoid generating call to Validate when attribute type does not define the method

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

Correctly use time.Format to convert DateTime value into string

---

goagen/gen_client/cli_generator.go
goagen/gen_client/cli_generator_test.go

Properly order path parameters when building path

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

Protect array validation against nil elements

---

goagen/codegen/validation.go

see https://github.com/goadesign/goa/pull/962#discussion_r92101541

Fix string type checking.

---

design/validation.go
design/validation_test.go

Use go/build to determine if package exists for validations.

---

design/apidsl/action.go
design/apidsl/resource_test.go

Fix potential panic when finalizing resource definitions

---

design/apidsl/type.go
design/apidsl/type_test.go
middleware/security/jwt/jwt_test.go

Properly compute element type of media type arrays

---

goagen/codegen/finalizer.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Assign to default param values.

---

design/apidsl/type.go
dslengine/runner_test.go

Handle use of empty types gracefully

---

goagen/gen_client/generator.go
goagen/gen_controller/generator.go
goagen/gen_js/generator.go
goagen/gen_main/generator.go
goagen/gen_schema/generator.go
goagen/gen_swagger/generator.go

This is a backporting of #1050 to v1.

Fix goagen to not call panic when API definition is missing

---

goagen/codegen/finalizer.go
goagen/codegen/finalizer_test.go

When building validations for recursive types

Protect against infinite recursions

---

error.go
error_test.go
middleware/error_handler_test.go
middleware/log_request_test.go

ErrorResponse matches ErrorMedia.

---

goagen/codegen/publicizer.go
goagen/codegen/publicizer_test.go
goagen/gen_app/writers_test.go

Add nil check in publicizer for hash

Add nil check for user type in gen_app (#1073)

---

error.go
error_test.go
middleware/error_handler_test.go
middleware/log_request_test.go

Same as #1080 but into v1 branch.

v1: ErrorResponse matches ErrorMedia.

---

design/apidsl/attribute.go
dslengine/runner.go

Make sure that reference type attributes have been computed
prior to building base attribute that relies on it.
Fix #1091

Fix Reference

---

design/apidsl/type.go

To illustrate use of `Reference`.

Update description of Type DSL function.

---

goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_app/test_generator_test.go

Fix #1125
Signed-off-by: Matteo Suppo <matteo.suppo@gmail.com>

Generate tests correctly when headers are defined only on resource

---

middleware/tracer.go

Do it at call time so that the same traced doer can be reused to do many
requests potentially concurrently.

Fix TraceDoer so it fetches the trace details properly.

---

design/definitions.go
design/definitions_test.go

Fix 'AllParams' so that it does not return parent query string params

---

design/definitions.go
design/definitions_test.go

Protect against nil resource Params field

---

design/definitions.go
design/definitions_test.go

Make sure resource query string params are returned

---

metrics.go
metrics_appengine.go

https://github.com/goadesign/goa/pull/1153
cherry picked v1 branch.
Verification please.

Fix problem not starting with appengine

---

goagen/gen_client/cli_generator_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

when building request in generated client package.
Fix #1165

Make sure Content-Type header is set

---

.travis.yml
middleware/xray/client.go
middleware/xray/middleware.go
middleware/xray/middleware_test.go
middleware/xray/segment.go
middleware/xray/transport.go
middleware/xray/transport_test.go

Note: This PR would break compatibility with Go1.6 since this code relies on accessing the context in http.Request.

Added Transport wrapper for xray tracing

---

goagen/gen_main/generator.go
goagen/gen_main/generator_test.go

Generate ListenAndServeTLS() in gen_main

---

codegen/files/service.go
codegen/files/service_test.go
codegen/generators/client.go
codegen/generators/server.go
codegen/types.go
codegen/types_test.go
design/media_type.go

Implement Service()

---

codegen/files/rest/server.go
codegen/files/rest/server_test.go
context.go
error.go
examples/account/gen/transport/http/account_server.go
rest/error.go
rest/middleware/debugging/middleware.go
rest/middleware/logging/middleware.go
rest/middleware/tracing/middleware.go
rest/mux.go

* Use latest httptreemux, take advantage of new NewContextMux function.
* Add adaptive sampling algorithm to trace middleware.

Misc fixes to goa library package

---

codegen/files/rest/json_schema.go
codegen/files/rest/openapi_v2_builder.go
codegen/files/rest/paths.go
codegen/files/rest/server.go
codegen/generators/server.go
design/generated.go
design/init.go
design/rest/action.go
design/rest/error.go
design/rest/init.go
design/rest/resource.go
design/rest/root.go
design/root.go
dsl/rest/description.go
eval/context.go
eval/expression.go

Properly finalize resources when running DSL

---

middleware/xray/middleware_test.go
middleware/xray/segment.go
middleware/xray/segment_test.go
middleware/xray/transport_test.go

@raphael set xray.Segment.Error to true when recording error unless Fault or Throttle already set

set Error in when recording

---

design/definitions.go

So that parent resources are evaluated first to make sure child resources can
look up the finalized parent path and query string parameters.
Fix #1202

Fix resource evaluation order

---

rest/middleware/tracing/middleware.go
rest/middleware/tracing/middleware_test.go
rest/middleware/tracing/sampler.go
rest/middleware/tracing/sampler_test.go

@raphael change tracing middleware to use Sampler defined separately
added unit tests for tracing middleware

tracing with adaptive sampler

---

design/apidsl/media_type.go
design/apidsl/media_type_test.go

This is a backporting of #1232 to v1.

Add an argument to CollectionOf() (#1232)

---

design/apidsl/attribute.go
design/example.go
goagen/codegen/validation.go
validation.go
validation_test.go

Support RFC1123 in the DSL Format

---

logging.go

Since there have been multiple PRs rejected on this line, I think a comment would make it clearer that the spelling is deliberate.

There is no typo in EROR

---

middleware/xray/middleware.go
middleware/xray/middleware_test.go

xray middleware to periodically redial daemon address because the IP address may change over time.

xray middleware to periodically redial daemon address

---

design/apidsl/api.go
design/apidsl/media_type.go
design/apidsl/type.go

TypeName is only valid when used in MediaType

---

_integration_tests/integration_test.go
_integration_tests/media/design/design.go
design/apidsl/attribute.go

Fix use of Reference for object types.

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Properly handle array path params

---

design/apidsl/action_test.go
design/definitions.go

Properly inherit required attributes when merging.

---

logging/logrus/adapter.go
logging/logrus/adapter_test.go

update logrus import path

---

design/definitions.go
design/definitions_test.go

sorry, it was easier for me to do the pull request again
Previous PR: #1285

keep trailing slashes on resource definition

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go

Properly handle array query string parameters

---

service.go
service_test.go

This is a backport of #1296 to v1.

Changeable FileSystem for FileHandler

---

goagen/codegen/validation.go
goagen/codegen/validation_test.go

This is a backport of #1298 to v1.

Fix to generate validations of hash elements

---

goagen/gen_app/test_generator.go

I found this was helpful when I was writing some testcases.

Made an error message in the test generator slightly more useful.

---

goagen/gen_app/test_generator.go

Pushing a change made to master branch to v1 branch

Made an error message slightly more useful - pushing change to v1

---

design/types.go
design/types_test.go

Fix example generated for projected collection media types.

---

design/definitions.go
design/types.go
design/types_test.go

Fix resource error response

---

goagen/codegen/workspace.go
goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
goagen/gen_client/cli_generator.go
goagen/gen_client/generator.go
goagen/gen_main/generator.go

To maintain backwards compatibility.

Rename Format into FormatCode

---

.golint_exclude
metrics.go
metrics_test.go

Update sink code to latest go-metrics interface

---

design/definitions.go
design/definitions_test.go

Protect attribute "Inherit" method from recursive type definitions.

---

error.go
error_test.go

Sorry for the late PR for master!

Add ability to customize errors response structure.

---

design/apidsl/type.go

Fix ArrayOf DSL usage docs.

---

error.go
error_test.go
mux.go
mux_test.go
service.go
service_test.go

This is a backport of #1374 to the v1 branch.
* Added Method Not Allowed default handler
* Changed MethodNotAllowed description comments
* MethodNotAllowed error distinguishes singular/plural

Backport of #1374 to v1

---

goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

* add missing linebreak to websocket client template
* updated ws client template test

Fixed ws client template (#1382)

---

encoding.go
encoding/gogoprotobuf/encoding.go
goagen/gen_app/writers.go
goagen/gen_client/generator.go
middleware/gzip/middleware.go
middleware/gzip/middleware_test.go
service.go

Merge improvements made to gzip middleware in master.

Merge gzip middleware improvements made in master.

---

middleware/gzip/middleware.go
middleware/gzip/middleware_test.go

gzip middleware updates

---

service.go

If multiple calls are made at once several will try to initialize and are racing to do so.

Sync MuxHandler init

---

middleware/security/jwt/jwt.go
middleware/security/jwt/jwt_test.go

Allow JWT scopes claim to be named 'scope' or 'scopes'

---

service.go

If multiple calls are made at once several will try to initialize and are racing to do so.

Sync MuxHandler init (#1400 -> v1)

---

goagen/utils/signal_appengine.go
goagen/utils/signal_lin.go

cherry-pick v1 https://github.com/goadesign/goa/pull/1405

Fix Correspondence of packages to be should excluded on appengine

---

validation_test.go

Add tests for goa.ValidateFormat()

---

dsl/validation_test.go

Add tests for the DSL Format

---

codegen/validation.go

Fix missing validate method

---

.gitignore
.travis.yml
Makefile
design/types.go
http/design/aliases.go

test_aliaser_travis

---

http/design/response.go

disallow_result_for_no_content

---

http/design/response.go

check_for_response_body

---

goagen/gen_main/generator.go
goagen/gen_main/generator_test.go

Return statement generated once v1

---

goagen/gen_main/generator.go
goagen/gen_main/generator_test.go

https://github.com/goadesign/goa/pull/1464

master: Return statement generated once

---

codegen/scope.go
codegen/service/service_data.go
design/api.go
examples/cellar/cmd/cellarsvc/main.go
examples/cellar/gen/http/sommelier/server/server.go
examples/cellar/gen/http/storage/server/server.go
examples/cellar/gen/http/swagger/server/server.go
examples/cellar/sommelier.go
examples/cellar/storage.go
examples/cellar/swagger.go
http/codegen/example_server.go
http/codegen/handler_test.go
http/codegen/server.go
http/codegen/server_init_test.go
http/codegen/service_data.go
http/codegen/testdata/server_dsls.go
http/codegen/testdata/server_init_functions.go

print_mounted_endpoints

---

design/apidsl/api.go

Just like #1471. 
Thanks for Goa btw - I'm still learning it but I plan to migrate my old Go backend into it. It look like it will greatly clean my existing code and help to have clean swagger always in sync! Actually I believe it's the best way to write micro-services, really.

extended usage help for Description function

---

validation_test.go

Add tests for goa.ValidatePattern()

---

metrics.go

Instead of running go-metrics, we dump metric collection earlier.
This also allows overriding go-metrics with a compatible collector.
Backwards compatible, so we keep the NoOpSink and associated stuff.
Only overhead to "no" metrics is key normalization.

Completely bypass metrics (->v1)

---

goagen/gen_app/test_generator.go

When parameters fail validation.
Fixes #1482

Properly return error from test helper

---

cmd/aliaser/ast.go
cmd/aliaser/main.go
cmd/goa/gen.go
codegen/generator/generate.go
design/mapped_attribute.go
eval/eval.go
http/design/response.go

Fixes aliaser tool when generating aliases for HTTP DSL

add_comments_http_response

---

goagen/gen_app/generator.go
goagen/gen_main/generator.go
goagen/gen_swagger/generator.go

Fix --notool option used with bootstrap

---

design/random.go
uuid/uuid.go

Fix #1490 by wrapping calls to uuid.NewV4() in uuid.Must() calls.

fix uuid breaking changes

---

design/random.go
uuid/uuid.go

Fix #1490 by wrapping calls to uuid.NewV4() in uuid.Must() calls.

fix uuid breaking changes in v1

---

cmd/aliaser/main.go

aliaser_dsl_flag

---

.travis.yml
Makefile

test_plugins_in_travis

---

http/codegen/client_body_types_test.go
http/codegen/client_types.go
http/codegen/testdata/result_dsls.go

Fixes #1522 
Fixes an issue where the code generation in client types does not generate a newline during some cases.

fix_client_types_codegen

---

design/result_type.go
dsl/result_type.go

Fix Extend for Result

---

examples/calc/gen/http/calc/client/client.go
examples/calc/gen/http/calc/client/encode_decode.go
examples/cellar/gen/http/sommelier/client/client.go
examples/cellar/gen/http/sommelier/client/encode_decode.go
examples/cellar/gen/http/storage/client/client.go
examples/cellar/gen/http/storage/client/encode_decode.go
http/codegen/client.go
http/codegen/service_data.go

Initialize HTTP request context in BuildX request function

---

design/api_test.go

Add tests for design.URLParams()

---

design/api_test.go

Add tests for design.ServerExpr.Validate()

---

design/attribute_test.go

Add tests for design.AttributeExpr.Validate()

---

design/attribute_test.go

Add tests for design.AttributeExpr.AllRequired()

---

design/attribute_test.go

Add tests for design.AttributeExpr.IsRequired()

---

examples/calc/gen/http/calc/client/cli.go
examples/calc/gen/http/cli/cli.go
examples/cellar/gen/http/cli/cli.go
examples/cellar/gen/http/sommelier/client/cli.go
examples/cellar/gen/http/storage/client/cli.go
http/codegen/client_cli.go
http/codegen/client_cli_test.go
http/codegen/testdata/parse_endpoint_functions.go

Fixes code generation issues in payload build code in CLI if the payload is of array/map of user types.

Fix CLI payload build code for array/map user type

---

design/attribute_test.go

Add tests for AttributeExpr.IsRequiredNoDefault()

---

codegen/transform.go

Fix codegen.AppendHelpers to not add already existing helper

---

design/attribute_test.go

Add tests for AttributeExpr.IsPrimitivePointer()

---

design/attribute_test.go

Add tests for AttributeExpr.HasDefaultValue()

---

design/attribute.go
dsl/validation.go

Check if validation format is supported

---

design/attribute.go
design/attribute_test.go
dsl/result_type.go

Check if attribute also exists in Bases (via Extend)

---

design/types_test.go

Add tests for design.IsPrimitive()

---

design/types_test.go

Add tests for design.Primitive.IsCompatible()

---

design/types_test.go

Add tests for design.Array.IsCompatible()

---

http/middleware/logging/log.go

Missed this change in the previous pr https://github.com/goadesign/goa/pull/1590

Removed [INFO]/[ERROR] from the log

---

design/apidsl/action.go
design/definitions.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_swagger/swagger.go

Related to https://github.com/goadesign/goa/issues/1270 (and #1565 for v2).
This pull request adds brand new DSLs `Multipart` and `OptionalMultipart`. It makes it possible to handle `multipart/form-data` using goa. I'v already done the test with https://github.com/goadesign/examples/tree/master/form_encoding but you might find some issues. I would appreciate any comments or suggestions.

Add a DSL MultipartForm

---

goagen/gen_app/generator.go

Add missing imports to generated controllers

---

codegen/transform.go
codegen/transform_test.go

Honor struct:field:name in transform

---

http/codegen/openapi/openapi_v2.go
http/codegen/openapi/openapi_v2_builder.go

Required by https://github.com/goadesign/plugins/pull/15

openapi fixes

---

codegen/service/convert.go
codegen/service/convert_test.go

Handle interface type in convert

---

http/design/endpoint.go

Use AttributeExpr.Find to find an attribute during Validate

---

design/types_test.go

Add tests for design.Object.IsCompatible() 

---

design/types_test.go

Add tests for design.Map.IsCompatible()

---

pkg/version.go
pkg/version_test.go

Add tests for pkg package

---

design/types_test.go

Add tests for design.QualifiedTypeName()

---

design/user_type_test.go

Add tests for design.UserTypeExpr.IsCompatible()

---

design/types_test.go

Add tests for design.AsObject()

---

design/project_test.go
design/result_type.go

Fix infinite recursion issue for recursive ResultType definitions

---

design/types_test.go

Add tests for design.AsArray()

---

codegen/transform.go
codegen/transform_test.go

Fix transforming nested maps

---

codegen/transform.go
codegen/transform_test.go

* Fixes mapDepth to return maps inside Object type.

Fix nested map transform

---

design/types_test.go

Add tests for design.AsMap()

---

codegen/plugin.go
codegen/plugin_test.go
eval/expression.go

Fixes https://github.com/goadesign/plugins/issues/32

Honor plugin dependencies during code generation

---

design/definitions.go
design/random.go
design/types.go
design/validation.go
design/validation_test.go
goagen/codegen/types.go
goagen/gen_app/generator.go
goagen/gen_app/generator_test.go
goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go

This is a backport of #1612 to v1.

Add a primitive type File

---

design/service_test.go

Add tests for design.ErrorExpr.Validate()

---

design/user_type.go
dsl/result_type.go

Implement support for TypeName in user types

---

dsl/error.go
examples/calc/gen/http/openapi.yaml
examples/cellar/gen/http/openapi.yaml

Fix error temporary

---

codegen/transform.go
codegen/transform_test.go

Fix nested array of maps

---

design/definitions.go

So that canonical action parameters are finalized.
Fix #1569

Make sure to finalize parent resources first.

---

design/attribute.go
http/codegen/client_cli.go
http/dsl/http.go

Changes required by https://github.com/goadesign/plugins/pull/38

Set token in header by default

---

design/method_test.go

Add tests for design.MethodExpr.Validate()

---

design/types_test.go

Add tests for design.IsObject()

---

design/result_type_test.go

Add tests for design.CanonicalIdentifier()

---

design/result_type_test.go

Add tests for design.ResultTypeExpr.IsError()

---

design/types_test.go

Add tests for design.IsArray()

---

goagen/gen_client/cli_generator.go

Fix serialization of default values for non string and non integer attributes.

---

design/types_test.go

Add tests for design.IsMap()

---

design/root_test.go

Add tests for design.RootExpr.Validate()

---

http/codegen/openapi/json_schema.go

Make Schema name optional when rendering YAML

---

codegen/service/endpoint.go
codegen/service/testdata/security_functions.go
examples/calc/gen/http/openapi.yaml
examples/cellar/gen/http/openapi.yaml
examples/error/gen/http/openapi.yaml
examples/security/gen/http/openapi.yaml
examples/security/gen/secured_service/endpoints.go

If corresponding payload attribute is not required.
Fixes #1686

Properly check for nil security credentials.

---

codegen/goify.go
codegen/types_test.go

Protect Goify against all invalid characters.

---

uuid/uuid.go

These are included in satori/go.uuid and must be added here due
to restrictions on adding new methods to non-local types.
The other alternative is for the user to declare a type alias,
but this will solve the issue for all goa users.

Add Scan and Value methods for UUID

---

design/root_test.go

Fix a test case for design.RootExpr.Validate()

---

design/api_test.go

Add tests for design.APIExpr.EvalName()

---

design/api_test.go

Add tests for design.ServerParamExpr.EvalName()

---

design/api_test.go

Add tests for design.APIExpr.Finalize()

---

_integration_tests/integration_test.go
error.go
goagen/codegen/publicizer_test.go
goagen/codegen/types.go
goagen/codegen/types_test.go
goagen/gen_app/writers_test.go
middleware/error_handler_test.go

* add a yaml tag to generated types fields
* yaml tag: add missing args
* update unit tests
* yaml tags, yaml tags everywhere
* unit tests: remove white space

add a yaml tag to generated types fields (#1727)

---

goagen/gen_swagger/swagger.go
goagen/gen_swagger/swagger_test.go

Fixes #1741 in accordance with https://swagger.io/docs/specification/2-0/file-upload/

Fix for v1 multipart/form-data Swagger semantic error

---

Makefile

now that it's properly go gettable again.

Remove lint git clone hack

---

design/api_test.go

Issue of https://github.com/goadesign/goa/issues/1703
I write design.APIExpr.Hash Test. 
Cloud you review this PR?

Issue#1703 Add tests for design.APIExpr.Hash()

---

goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger_test.go

Fix minItems/maxItems for array type in a generated JSON schema (#1768).

---

design/types.go
goagen/gen_swagger/swagger_test.go

Hello, 
I fixed #1764, but I'm not sure that this modification needs one test only.
Thanks

Fix recursive types (#1764)

---

Makefile

Hello,
It's a backport of commit 074ca3f24588bb8e32d539535273de161d6194d7.
Thanks

Backport to v1: Fix gocyclo dependency

---

goagen/gen_schema/json_schema.go
goagen/gen_swagger/swagger_test.go

Hello,
It's a backport of #1769.
Thanks

Backport to v1: Fix minItems/maxItems for array type (#1769)

---

design/types.go
goagen/gen_swagger/swagger_test.go

Hello,
It's a backport of #1765.
Thanks

Backport to v1: Fix recursive types (#1765)

---

http/codegen/openapi/openapi_v2_builder.go

Fix "swagger:summary"

---

design/types.go
goagen/gen_swagger/swagger_test.go

Fix design.HasFile for recursive user types

---

design/apidsl/attribute.go
design/example.go
goagen/codegen/validation.go
validation.go
validation_test.go

Hello,
It's a backport of #1780.
Thanks

Backport to v1: Add RFC3339 date format (#1780)

---

http/codegen/client_body_types_test.go
http/codegen/client_types.go
http/codegen/server.go
http/codegen/service_data.go
http/codegen/testdata/result_encode_functions.go

Fix initializing client response type when explicit body specified

---

design/types.go
goagen/gen_swagger/swagger_test.go

Hello,
It's a backport of #1789.
Thanks

Backport to v1: Fix design.HasFile for recursive user types (#1789)

---

middleware/security/jwt/jwt.go
middleware/security/jwt/jwt_test.go

This adds support for extracting the JWT token from the query parameter. How does it look?

Add support for JWT Token authorization via query parameter

---

codegen/validation.go
design/attribute.go
design/example.go
dsl/validation.go
dsl/validation_test.go
http/design/aliases.go
http/dsl/aliases.go
validation.go
validation_test.go

Hello,
It's a backport of #1780.
Thanks

Backport to v2: Add RFC3339 date format

---

design/example.go
http/design/response.go

Allow response with status 101 to define streaming result type.

Allow non empty response body for streaming results

---

codegen/transform.go
codegen/transform_test.go

Type cast default values

---

codegen/service/service_data.go
design/mapped_attribute.go
design/method.go
design/method_test.go
eval/eval.go
eval/expression.go
http/codegen/openapi/json_schema.go
http/codegen/openapi/openapi_v2_builder.go
http/codegen/openapi_test.go
http/codegen/service_data.go
http/design/body_types.go
http/design/endpoint.go
http/design/response.go
http/design/response_test.go
http/design/root.go
http/design/service.go
http/dsl/http.go

Inherit security requirements at design time so that code generation works properly for computed security headers.
Fix #1811

Fix service requirements

---

codegen/generator/openapi.go

Checking contribution ease-fullness

Remove redundant variables declaration

---

design/api.go
http/codegen/server.go
http/codegen/service_data.go

Properly handle path relatively to request path.
Fix #1824

Fix directory based file servers

---

http/codegen/server.go
http/codegen/testdata/multipart_code.go

Fixes code build when using design from https://github.com/goadesign/plugins/issues/52

Fix "err redefined" error using multipart request

---

codegen/service/testdata/convert_functions.go
codegen/service/testdata/create_functions.go
codegen/transform.go
codegen/transform_test.go
examples/cellar/gen/http/sommelier/client/cli.go
examples/cellar/gen/http/sommelier/client/types.go
examples/cellar/gen/http/sommelier/server/types.go
examples/cellar/gen/http/storage/client/cli.go
examples/cellar/gen/http/storage/client/types.go
examples/cellar/gen/http/storage/server/types.go
examples/cellar/gen/sommelier/service.go
examples/cellar/gen/storage/service.go

* Count target "[" instances rather than "." to determine array depth
* Updated test code strings to expect "i" as the first array index variable
* Regenerated examples

Fix nested array index variables (#1828)

---

design/types.go

Fix infinite recursion in file attribute detection
Fixes #1834

Fix infinite recursion in file attribute detection

---

examples/cellar/gen/http/sommelier/server/types.go
examples/cellar/gen/http/storage/server/types.go
http/codegen/server_types.go
http/codegen/service_data.go

Remove redeclaration of collection types in server 

---

design/method_test.go

issue of [#1796](https://github.com/goadesign/goa/issues/1796).
I challenged writing a test.
thank you.

Add tests for design.MethodExpr.EvalName()

---

design/service_test.go

- [#1797](https://github.com/goadesign/goa/issues/1797)
- [#1798](https://github.com/goadesign/goa/issues/1798)
- [#1799](https://github.com/goadesign/goa/issues/1799)

Added test code for three issues

---

goagen/gen_app/writers.go
goagen/gen_app/writers_test.go
goagen/gen_client/generator.go
goagen/gen_client/generator_test.go

bugfix for issue #1862
this PR is for master branch. previous PR for v1 is #1863
* bugfix type error in multipart-form payload
* bugfix Array attribute error in multipartform
* fix wrong comment line and add comment to new function
* fix fromString func to do not cause panic and support some other types for array element

bugfix type error in multipart-form payload

---

design/security_test.go

Add tests for design.FlowExpr.Validate()

---

design/method.go
design/method_test.go

Fix Security for using in a Service expression (#1872)

---

cmd/aliaser/main.go
cmd/goa/gen.go
codegen/sections_test.go
codegen/service/client.go
codegen/service/convert_test.go
codegen/service/endpoint.go
codegen/service/testdata/convert_dsls.go
codegen/service/testdata/create_dsls.go
codegen/testing.go
design/project_test.go
design/result_type.go
design/server.go
design/types.go
dsl/security.go
http/codegen/example_cli.go
http/codegen/openapi.go
http/middleware/requestid_test.go
http/middleware/xray/net_conn_testing.go
pkg/version.go
pkg/version_test.go
validation_test.go

This pr contains style fixes like import sorting, removing redundant parentheses etc.

fix some linter's  warnings

---

codegen/service/convert.go
codegen/service/convert_test.go

Fix import of a package from the "vendor" directory when the "ConvertTo" is used

---

http/codegen/openapi/openapi_v2.go
http/codegen/openapi_test.go
http/codegen/testdata/openapi_v2/TestExtensions/endpoint_file0.golden
http/codegen/testdata/openapi_v2/TestExtensions/endpoint_file1.golden

Fix writing of swagger extensions into openapi.yaml (#1896)

---

security/scheme.go

Scopes typo

---

goagen/gen_js/doc.go
goagen/gen_js/generator.go

`mzabriskie/axios` moved to `axios/axios`.
And fixed the link described about axios config.
Thanks

docs(js): mzabriskie/axios repository moved to axios/axios

---

examples/calc/gen/http/calc/server/server.go
examples/cellar/gen/http/sommelier/server/server.go
examples/cellar/gen/http/storage/server/server.go
examples/chatter/gen/http/chatter/server/server.go
examples/error/gen/http/divider/server/server.go
examples/security/gen/http/secured_service/server/server.go
http/codegen/server.go
http/codegen/testdata/handler_init_functions.go
http/codegen/testdata/streaming_code.go

Properly handle errors due to incorrect HTTP parameters.

Fix handling of validation errors in HTTP decode

---

docs/ErrorHandling.md

Fix description related to creating custom error types.
Fix #1852

Adjust error handling docs

---

expr/service_test.go

Add tests for design.ServiceExpr.Validate()

---

dsl/http.go
dsl/payload.go
expr/attribute.go
expr/http_endpoint_test.go
http/codegen/server_decode_test.go
http/codegen/testdata/payload_decode_functions.go
http/codegen/testdata/payload_dsls.go

Fix explicit Body definition with extended Type

---

expr/http_endpoint.go
http/codegen/server_decode_test.go
http/codegen/testdata/payload_decode_functions.go
http/codegen/testdata/payload_dsls.go

Check bases and references in validation phase (#1943)

---

expr/attribute.go
expr/attribute_test.go

Add tests for ValidationExpr.HasRequiredOnly() 

---

codegen/server/example_cli.go
codegen/server/testdata/example_cli_code.go
dsl/description.go
dsl/doc.go
dsl/grpc.go
dsl/headers.go
dsl/http.go
dsl/response.go
expr/api.go
expr/grpc.go
expr/grpc_endpoint.go
expr/grpc_error.go
expr/grpc_response.go
expr/grpc_service.go
expr/helpers.go
expr/http_endpoint.go
expr/method.go
expr/root.go
expr/security.go
expr/server.go
expr/testing.go
http/codegen/testdata/payload_decode_functions.go

gRPC support Part 1 of 2.
This PR contains only the dsls and expressions for gRPC. Code generation will be issued in a separate PR.

Add support for gRPC expressions

---

expr/server.go
expr/server_test.go

Add tests for expr.HostExpr.Validate()

---

codegen/go_transform.go
examples/calc/gen/grpc/calc/server/server.go
examples/chatter/gen/grpc/chatter/client/client.go
examples/chatter/gen/grpc/chatter/client/encode_decode.go
examples/chatter/gen/grpc/chatter/server/server.go
examples/chatter/gen/http/chatter/client/client.go
examples/chatter/gen/http/chatter/server/server.go
examples/error/gen/grpc/divider/server/server.go
examples/security/gen/grpc/secured_service/server/server.go
grpc/codegen/client.go
grpc/codegen/client_cli.go
grpc/codegen/client_test.go
grpc/codegen/protobuf_transform.go
grpc/codegen/protobuf_transform_test.go
grpc/codegen/server.go
grpc/codegen/testdata/client_endpoint_init_code.go
grpc/codegen/testdata/server_interface_code.go
grpc/handler.go
http/codegen/client_cli.go
http/codegen/service_data.go
http/codegen/testdata/streaming_code.go

This PR contains fixes to gRPC codegen found during testing by starting a real gRPC server generated by goa v2.
We should have some integration tests in goa v2 which would have caught these issues.

Grpc fixes

---

codegen/service/example_svc.go
codegen/validation.go
grpc/codegen/server.go
grpc/codegen/service_data.go
grpc/codegen/testdata/streaming_code.go

Grpc validate fixes

---

codegen/service/service_test.go
codegen/service/testdata/service_code.go
codegen/service/testdata/service_dsls.go
expr/dup.go

Dup Meta expression

---

expr/security_test.go

Add tests for expr.SchemeExpr.Validate()

---

design/random.go
design/types.go
goagen/gen_app/generator.go
goagen/gen_app/test_generator.go
uuid/uuid.go
uuid/uuid_js.go

satori's package isn't being maintained anymore.

Use gofrs/uuid instead of satori/go.uuid

---

expr/security_test.go

Improve tests for expr.SchemeExpr.Type()

---

expr/security_test.go

Improve tests for expr.FlowExpr.Type()

---

expr/service_test.go

Add tests for expe.ServiceExpr.Method()

---

expr/result_type_test.go

Add tests for expr.ViewExpr.EvalName()

---

expr/attribute_test.go

Improve tests for IsPrimitivePointer() of expr.AttributeExpr

---

expr/http_body_types.go
expr/http_endpoint.go
http/codegen/client_body_types_test.go
http/codegen/server_types_test.go
http/codegen/testdata/payload_decode_functions.go
http/codegen/testdata/payload_dsls.go

Fix duplicate payload type definitions

---

expr/security_test.go

Add tests for expr.SchemeKind.String()

---

expr/method_test.go

Add tests for expr.MethodExpr.IsPayloadStreaming()

---

expr/http_endpoint.go
http/codegen/client_body_types_test.go
http/codegen/server_types_test.go
http/codegen/testdata/payload_dsls.go

Fix header attribute validated in the body

---

expr/attribute_test.go

*What does this PR do?*
* This PR adds tests for the function expr.AttributeExpr.EvalName(), as laid out in the issue #1957. 
Please tell me if there's any issues :)

Add tests for expr.AttributeExpr.EvalName()

---

expr/api_test.go

This solves issues #1705 and #1704 by adding tests for these two functions.
If there is any issues, feel free to give me a shout :)

Add tests for expr.DocsExpr.EvalName() and expr.ContactExpr.EvalName()

---

expr/result_type_test.go

Add tests for expr.ResultTypeExpr.View()

---

expr/types_test.go

Add tests for expr.Object.Rename()

---

expr/service_test.go

Add tests for expr.ServiceExpr.Error()

---

codegen/server/docs.go
dsl/api.go
dsl/attribute.go
dsl/doc.go
dsl/error.go
dsl/grpc.go
dsl/payload.go
dsl/result_type.go
dsl/server.go
dsl/value.go
expr/api.go
expr/attribute.go
expr/docs.go
expr/example.go
expr/grpc_endpoint.go
expr/grpc_error.go
expr/grpc_response.go
expr/http_endpoint.go
expr/http_service.go
expr/result_type.go
expr/result_type_test.go
expr/root.go
expr/security.go
expr/server.go
expr/testing.go
expr/types.go
expr/user_type.go

Updates godocs for `eval`, `dsl`, and `expr` packages.

Godoc updates dsl pkg

---

codegen/example/example_server.go
codegen/example/example_server_test.go
codegen/example/testdata/example_server_code.go
codegen/service/auth_funcs.go
codegen/service/client.go
codegen/service/endpoint.go
codegen/service/example_svc.go
codegen/service/service.go
codegen/service/service_test.go
codegen/service/testdata/service_code.go
codegen/service/testdata/service_dsls.go
codegen/service/views.go
grpc/codegen/client.go
grpc/codegen/client_cli.go
grpc/codegen/client_types.go
grpc/codegen/example_server.go
grpc/codegen/proto.go
grpc/codegen/server.go
grpc/codegen/server_types.go
http/codegen/client.go
http/codegen/client_cli.go
http/codegen/client_types.go
http/codegen/example_server.go
http/codegen/paths.go
http/codegen/server.go
http/codegen/server_types.go
http/codegen/service_data.go
http/codegen/testdata/multipart_code.go
http/codegen/testdata/server_init_functions.go

Fix space in service name

---

expr/method_test.go

Add tests for expr.MethodExpr.Error()

---

expr/grpc_endpoint.go
expr/grpc_endpoint_test.go
expr/http_endpoint_test.go
expr/http_response_test.go
expr/testdata/endpoint_dsls.go
expr/testing.go
grpc/codegen/testing.go
http/codegen/client_body_types_test.go
http/codegen/testing.go

Error during validation if Any type used in gRPC endpoint

---

.travis.yml
appveyor.yml
grpc/codegen/proto.go
grpc/codegen/service_data.go
grpc/codegen/testdata/request_decoder_code.go
grpc/codegen/testdata/response_decoder_code.go
grpc/codegen/testdata/streaming_code.go
http/codegen/openapi.go
http/codegen/testdata/openapi_v2_dsls.go

Grpc type duplication fix

---

codegen/go_transform.go
codegen/transformer.go
grpc/codegen/protobuf_transform.go

The fix is not perfect but gets the job done. We need to revisit transform code to make it better.

Fix transform code for helper functions

---

expr/http_endpoint.go
expr/root.go
expr/server.go
http/codegen/openapi/json_schema.go
http/codegen/openapi/openapi_v2_builder.go
http/codegen/openapi_test.go
http/codegen/service_data.go
http/codegen/testdata/openapi_v2_dsls.go

Walk server expressions for validating and finalizing server expressions

---

expr/result_type_test.go

Add tests for ResultTypeExpr.HasMultipleViews()

---

codegen/service/example_svc.go
grpc/codegen/proto.go
grpc/codegen/proto_test.go
grpc/codegen/testdata/proto_code.go

Fixes https://github.com/goadesign/goa/issues/2047

Use gRPC service name as proto package name to fix duplicate proto type registration

---

grpc/codegen/proto_test.go
grpc/codegen/service_data.go
grpc/codegen/testdata/dsls.go
grpc/codegen/testdata/proto_code.go

Fix gRPC codegen panic when multiple methods return same type

---

expr/example.go
expr/example_test.go
expr/testdata/example_test_dsls.go

Override example when using Reference

---

codegen/cli/cli.go
dsl/http.go
expr/attribute.go
expr/http_endpoint.go
http/codegen/client_decode_test.go
http/codegen/server_encode_test.go
http/codegen/service_data.go
http/codegen/testdata/result_decode_functions.go
http/codegen/testdata/result_dsls.go
http/codegen/testdata/result_encode_functions.go

Fix codegen panic when response body set to result type collection

---

codegen/service/service.go
codegen/service/service_test.go
codegen/service/testdata/service_code.go
codegen/service/testdata/service_dsls.go
expr/attribute.go
expr/method.go
expr/method_test.go
expr/security.go
expr/security_test.go
expr/service.go
expr/service_test.go
expr/testdata/method_validate_dsls.go
expr/testdata/service_validate_dsls.go
expr/testing.go
grpc/codegen/client.go
grpc/codegen/client_test.go
grpc/codegen/client_types.go
grpc/codegen/server.go
grpc/codegen/server_types.go
grpc/codegen/service_data.go
grpc/codegen/testdata/client_endpoint_init_code.go
grpc/codegen/testdata/dsls.go
grpc/codegen/testdata/server_interface_code.go
grpc/error.go

Support custom errors gRPC

---

grpc/codegen/client.go
grpc/codegen/client_types.go
grpc/codegen/client_types_test.go
grpc/codegen/server_types.go
grpc/codegen/server_types_test.go
grpc/codegen/service_data.go
grpc/codegen/testdata/client_endpoint_init_code.go
grpc/codegen/testdata/client_type_code.go
grpc/codegen/testdata/dsls.go
grpc/codegen/testdata/server_type_code.go

Fix type name when generating error type validation

---

expr/user_type_test.go

Add tests for expr.UserTypeExpr.Name()

---

grpc/codegen/service_data.go

The validation generation code tracks whether the validation is for server or client code.
It also detects whether a type is used in both.
Finally the code protects against infinite recursions by checking whether a given type has already been processed.
However if the type contains attributes using other user types then recursion check causes the code to bypass the server vs client check.
This means that in some cases child type validation functions may be missing for server or client.
This fix forces the code to recurse if the code is being generated for a different "side" (client vs server).
Fix #2088

Fix recurse validation

---

grpc/codegen/service_data.go

The validation generation code tracks whether the validation is for server or client code.
It also detects whether a type is used in both.
Finally the code protects against infinite recursions by checking whether a given type has already been processed.
However if the type contains attributes using other user types then recursion check causes the code to bypass the server vs client check.
This means that in some cases child type validation functions may be missing for server or client.
This fix forces the code to recurse if the code is being generated for a different "side" (client vs server).
Fix #2088

Fix missing validation functions.

---

expr/http_endpoint.go
expr/http_endpoint_test.go
expr/testdata/endpoint_dsls.go

Validate presence of secure token

---

expr/attribute.go
expr/http_endpoint_test.go
expr/testdata/endpoint_dsls.go

Properly validate inherited security tokens
